<style type="text/css">
.hr{
    color: #f00;
    background-color: orange;
    height: 2px; width: 100px;
}

/* about us */
.about-inner-column h4 {
    font-size: 2.5em;
    color: #FFD001;
    font-family: 'Marvel-Regular';
}
.about-inner-column p {
    font-size: 1.1em;
    color: #333333;
    line-height: 1.8em;
    margin: 1em 0 0;
}

.about-inner-column ul li a {
    color: #333333;
    font-size: 1.1em;
    padding-left: 2em;
}
.about-right img {
    width: 100%;
}

/* what we do */
section .section-title{
    text-align:center;
    margin-top:50px;
    text-transform:uppercase;
}
#what-we-do{
    background:#ffffff;
}
#what-we-do .card{
    padding: 1rem!important;
    border: none;
    margin-bottom:1rem;
    -webkit-transition: .5s all ease;
    -moz-transition: .5s all ease;
    transition: .5s all ease;
}
#what-we-do .card:hover{
    -webkit-box-shadow: 5px 7px 9px -4px rgb(158, 158, 158);
    -moz-box-shadow: 5px 7px 9px -4px rgb(158, 158, 158);
    box-shadow: 5px 7px 9px -4px rgb(158, 158, 158);
}
#what-we-do .card .card-block{
    padding-left: 50px;
    position: relative;
}
#what-we-do .card .card-block a{
    color: #007b5e !important;
    font-weight:700;
    text-decoration:none;
}
#what-we-do .card .card-block a i{
    display:none;
    
}
#what-we-do .card:hover .card-block a i{
    display:inline-block;
    font-weight:700;
    
}
#what-we-do .card .card-block:before{
    font-family: FontAwesome;
    position: absolute;
    font-size: 39px;
    color: #007b5e;
    left: 0;
    -webkit-transition: -webkit-transform .2s ease-in-out;
    transition:transform .2s ease-in-out;
}
#what-we-do .card .block-1:before{
    content: "\f0e7";
}
#what-we-do .card .block-2:before{
    content: "\f0eb";
}
#what-we-do .card .block-3:before{
    content: "\f00c";
}
#what-we-do .card .block-4:before{
    content: "\f209";
}
#what-we-do .card .block-5:before{
    content: "\f0a1";
}
#what-we-do .card .block-6:before{
    content: "\f218";
}
#what-we-do .card:hover .card-block:before{
    -webkit-transform: rotate(360deg);
    transform: rotate(360deg);  
    -webkit-transition: .5s all ease;
    -moz-transition: .5s all ease;
    transition: .5s all ease;
}

/* our team */
.row.heading h2 {
    text-align:center;
    margin-top:50px;
    text-transform:uppercase;
}
ul{
  margin:0;
  padding:0;
  list-style:none;
}
.heading.heading-icon {
    display: block;
}
.padding-lg {
    display: block;
    padding-top: 60px;
    padding-bottom: 60px;
}
.practice-area.padding-lg {
    padding-bottom: 55px;
    padding-top: 55px;
}
.practice-area .inner{ 
     border:1px solid #999999; 
     text-align:center; 
     margin-bottom:28px; 
     padding:40px 25px;
}
.our-webcoderskull .cnt-block:hover {
    box-shadow: 0px 0px 10px rgba(0,0,0,0.3);
    border: 0;
}
.practice-area .inner h3{ 
    color:#3c3c3c; 
    font-size:24px; 
    font-weight:500;
    font-family: 'Poppins', sans-serif;
    padding: 10px 0;
}
.practice-area .inner p{ 
    font-size:14px; 
    line-height:22px; 
    font-weight:400;
}
.practice-area .inner img{
    display:inline-block;
}


.our-webcoderskull{
  background: url("http://www.webcoderskull.com/img/right-sider-banner.png") no-repeat center top / cover;
  
}
.our-webcoderskull .cnt-block{ 
   float:left; 
   width:100%; 
   background:#fff; 
   padding:30px 20px; 
   text-align:center; 
   border:2px solid #d5d5d5;
   margin: 0 0 28px;
}
.our-webcoderskull .cnt-block figure{
   width:148px; 
   height:148px; 
   border-radius:100%; 
   display:inline-block;
   margin-bottom: 15px;
}
.our-webcoderskull .cnt-block img{ 
   width:148px; 
   height:148px; 
   border-radius:100%; 
}
.our-webcoderskull .cnt-block h3{ 
   color:#2a2a2a; 
   font-size:20px; 
   font-weight:500; 
   padding:6px 0;
   text-transform:uppercase;
}
.our-webcoderskull .cnt-block h3 a{
  text-decoration:none;
    color:#2a2a2a;
}
.our-webcoderskull .cnt-block h3 a:hover{
    color:#337ab7;
}
.our-webcoderskull .cnt-block p{ 
   color:#2a2a2a; 
   font-size:13px; 
   line-height:20px; 
   font-weight:400;
}
.our-webcoderskull .cnt-block .follow-us{
    margin:10px 0 0;
}
.our-webcoderskull .cnt-block .follow-us li{ 
    display:inline-block; 
    width:auto; 
    margin:0 5px;
}
.our-webcoderskull .cnt-block .follow-us li .fa{ 
   font-size:20px; 
   color:#767676;
}
.our-webcoderskull .cnt-block .follow-us li .fa:hover{ 
   color:#025a8e;
}


</style>

<br><br><br>
<section id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading text-uppercase">Про нас</h2>
                <hr class="hr">
                <h4 class="section-subheading text-muted ">A wonderful designs has takenpossession but also the leap into electronic pesetting industry  It was popularised in the 1960s with the release.</h4>
            </div>
            <div class="about-inner-section">                
                <div class="col-md-6 about-inner-column">
                    <h4>Eco friendly food is good for health </h4>
                    <p>Takenpossession of lorem Ipsum is simply dummy text of the printing and typesetting industry In sit amet sapien eros Integer  in tincidunt labore et dolore magna aliqua  remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.</p>
                    <ul>
                        <li><a href="#">Donec ut quam lscele volutri.</a></li>
                        <li><a href="#">Etiam volutpatbh quam bortis</a></li>
                        <li><a href="#">Varius fusce vit aeblandit.</a></li>
                    </ul>
                </div>
                <div class="col-md-6 about-right">
                <img src="https://images.pexels.com/photos/7096/people-woman-coffee-meeting.jpg?w=940&h=650&auto=compress&cs=tinysrgb" alt=" ">
            </div>
                <div class="clearfix"> </div>
        </div>
    </div>
</section>
<section id="what-we-do">
        <div class="container-fluid">
            <h2 class="section-title mb-2 h1 section-heading text-uppercase">What we do</h2>
            <hr class="hr">
            <p class="text-center text-muted h5">Having and managing a correct marketing strategy is crucial in a fast moving market.</p>
            <div class="row mt-5">
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 col-xl-4">
                    <div class="card">
                        <div class="card-block block-1">
                            <h3 class="card-title">Special title</h3>
                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                            <a href="javascript:void();" title="Read more" class="read-more" >Read more<i class="fa fa-angle-double-right ml-2"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 col-xl-4">
                    <div class="card">
                        <div class="card-block block-2">
                            <h3 class="card-title">Special title</h3>
                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                            <a href="javascript:void();" title="Read more" class="read-more" >Read more<i class="fa fa-angle-double-right ml-2"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 col-xl-4">
                    <div class="card">
                        <div class="card-block block-3">
                            <h3 class="card-title">Special title</h3>
                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                            <a href="javascript:void();" title="Read more" class="read-more" >Read more<i class="fa fa-angle-double-right ml-2"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 col-xl-4">
                    <div class="card">
                        <div class="card-block block-4">
                            <h3 class="card-title">Special title</h3>
                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                            <a href="javascript:void();" title="Read more" class="read-more" >Read more<i class="fa fa-angle-double-right ml-2"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 col-xl-4">
                    <div class="card">
                        <div class="card-block block-5">
                            <h3 class="card-title">Special title</h3>
                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                            <a href="javascript:void();" title="Read more" class="read-more" >Read more<i class="fa fa-angle-double-right ml-2"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 col-xl-4">
                    <div class="card">
                        <div class="card-block block-6">
                            <h3 class="card-title">Special title</h3>
                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                            <a href="javascript:void();" title="Read more" class="read-more" >Read more<i class="fa fa-angle-double-right ml-2"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>  
</section>
<section class="our-webcoderskull padding-lg">
  <div class="container">
    <div class="row heading heading-icon">
        <h2 class="section-title mb-2 h1 section-heading text-uppercase">our team</h2>
        <hr class="hr">
    </div>
    <ul class="row">
      <li class="col-12 col-md-6 col-lg-3">
          <div class="cnt-block equal-hight" style="height: 349px;">
            <figure><img src="http://ssl.gstatic.com/accounts/ui/avatar_2x.png" class="img-responsive" alt=""></figure>
            <h3><a href="http://www.webcoderskull.com/">Guptam Holla</a></h3>
            <p>Hofstra University School of Law Hempstead, New York</p>
            <ul class="follow-us clearfix">
              <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
              <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
            </ul>
          </div>
      </li>
      <li class="col-12 col-md-6 col-lg-3">
          <div class="cnt-block equal-hight" style="height: 349px;">
            <figure><img src="http://ssl.gstatic.com/accounts/ui/avatar_2x.png" class="img-responsive" alt=""></figure>
            <h3><a href="http://www.webcoderskull.com/">Omin Goshu</a></h3>
            <p>Hofstra University School of Law Hempstead, New York</p>
            <ul class="follow-us clearfix">
              <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
              <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
            </ul>
          </div>
       </li>
      <li class="col-12 col-md-6 col-lg-3">
          <div class="cnt-block equal-hight" style="height: 349px;">
            <figure><img src="http://ssl.gstatic.com/accounts/ui/avatar_2x.png" class="img-responsive" alt=""></figure>
            <h3><a href="http://www.webcoderskull.com/">Omin Goshu</a></h3>
            <p>Hofstra University School of Law Hempstead, New York</p>
            <ul class="follow-us clearfix">
              <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
              <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
            </ul>
          </div>
       </li>
      <li class="col-12 col-md-6 col-lg-3">
          <div class="cnt-block equal-hight" style="height: 349px;">
            <figure><img src="http://ssl.gstatic.com/accounts/ui/avatar_2x.png" class="img-responsive" alt=""></figure>
            <h3><a href="http://www.webcoderskull.com/">NArman Bandhu</a></h3>
            <p>Hofstra University School of Law Hempstead, New York</p>
            <ul class="follow-us clearfix">
              <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
              <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
            </ul>
          </div>
      </li>
      <li class="col-12 col-md-6 col-lg-3">
          <div class="cnt-block equal-hight" style="height: 349px;">
            <figure><img src="http://ssl.gstatic.com/accounts/ui/avatar_2x.png" class="img-responsive" alt=""></figure>
            <h3><a href="http://www.webcoderskull.com/">Guptam Holla</a></h3>
            <p>Hofstra University School of Law Hempstead, New York</p>
            <ul class="follow-us clearfix">
              <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
              <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
            </ul>
          </div>
      </li>
      <li class="col-12 col-md-6 col-lg-3">
          <div class="cnt-block equal-hight" style="height: 349px;">
            <figure><img src="http://ssl.gstatic.com/accounts/ui/avatar_2x.png" class="img-responsive" alt=""></figure>
            <h3><a href="#">Kappua Billa</a></h3>
            <p>Hofstra University School of Law Hempstead, New York</p>
            <ul class="follow-us clearfix">
              <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
              <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
            </ul>
          </div>
      </li>
      <li class="col-12 col-md-6 col-lg-3">
          <div class="cnt-block equal-hight" style="height: 349px;">
            <figure><img src="http://ssl.gstatic.com/accounts/ui/avatar_2x.png" class="img-responsive" alt=""></figure>
            <h3><a href="http://www.webcoderskull.com/">Omin Goshu</a></h3>
            <p>Hofstra University School of Law Hempstead, New York</p>
            <ul class="follow-us clearfix">
              <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
              <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
            </ul>
          </div>
       </li>
      <li class="col-12 col-md-6 col-lg-3">
          <div class="cnt-block equal-hight" style="height: 349px;">
            <figure><img src="http://ssl.gstatic.com/accounts/ui/avatar_2x.png" class="img-responsive" alt=""></figure>
            <h3><a href="http://www.webcoderskull.com/">NArman Bandhu</a></h3>
            <p>Hofstra University School of Law Hempstead, New York</p>
            <ul class="follow-us clearfix">
              <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
              <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
            </ul>
          </div>
      </li>
    </ul>
  </div>
</section>
<section id="adress">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading text-uppercase">Наша адреса</h2>
                <hr class="hr">
            </div>
            <div class="col-lg-12">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5440390.4847436575!2d26.69284185217994!3d48.255893698868164!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40d1d9c154700e8f%3A0x1068488f64010!2sUkraine!5e0!3m2!1sen!2sus!4v1545295695788" width="100%" height="350" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
        </div>
    </div>
</section>