  <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl() ?>/plugins/animate/animate.css">
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl() ?>/plugins/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl() ?>/plugins/animsition/css/animsition.min.css">
<!--==================================================================/=============================-->
  <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl() ?>/plugins/select2/select2.min.css">
<!--==================================================================/=============================-->
  <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl() ?>/plugins/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl() ?>/css/util.css">
  <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl() ?>/css/main.css">

  <script src="<?= $this->baseUrl() ?>/plugins/animsition/js/animsition.min.js"></script>
  <script src="<?= $this->baseUrl() ?>/plugins/select2/select2.min.js"></script>
<!--===============================================================================================-->
  <script src="<?= $this->baseUrl() ?>/plugins/daterangepicker/moment.min.js"></script>
  <script src="<?= $this->baseUrl() ?>/plugins/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
  <script src="<?= $this->baseUrl() ?>/plugins/countdowntime/countdowntime.js"></script>

<br><br><br>
<section id="contact">
    <div class="container">
      <div class="row">
      	<div class="container-fluid">
           
      	</div>
      </div>
      

	    <h2 class="text-center" id="form-header"><i class="fa fa-envelope"></i> Форма зворотнього звязку</h2>
	    <div class="row justify-content-center center">
			  <div class="col-12 col-md-8 col-lg-6 pb-5">
				  <form action="mail.php" method="post" class="form-horizontal">
            
        </div>
      </div>
    </div>
</section>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>
<div id="dropDownSelect1"></div>
<div class="container">
<div class="row">
      <div class="col-md-2"> </div>
      <div class="col-md-8">
        <h2 class="section-title mb-2 h1 section-heading text-uppercase text-center">Контактна інформація!</h2>
        <hr class="hr">
        <p class="mb-5 text-center">Маєте якісь побажання, або готові почати з нами наступний проект? Це чудово! Передзвоніть нам або надішліть нам електронний лист, і ми зв'яжемося з вами якомога швидше!</p>
        <div class="about-inner-section">                
          <div class="col-lg-6 mr-auto text-center about-inner-column">
            <i class="fa fa-envelope-o fa-2x mb-1 sr-contact"></i>
            <p>feedback@sample.com</p>
          </div>
          <div class="col-lg-6 ml-auto text-center about-right">
            <i class="fa fa-phone fa-2x mb-1 sr-contact"></i>
            <p>123-456-6789</p>
          </div>
        </div>
      </div>
      <div class="clearfix"></div>
      <br>
      <p class="mb-5 text-center">Або скористайтесь нашою формою зворотнього звязку</p>
      </div>


<div class="container-contact100">
    <div ></div>

    <button class="contact100-btn-show">
      <i class="fa fa-envelope-o" aria-hidden="true"></i>
    </button>

    <div class="wrap-contact100">
      <button class="contact100-btn-hide">
        <i class="fa fa-close" aria-hidden="true"></i>
      </button>

      <form class="contact100-form validate-form">
        <span class="contact100-form-title">
          
        </span>

        <div class="wrap-input100 rs1-wrap-input100 validate-input" data-validate="Name is required">
          <span class="label-input100">Ім'я</span>
          <input class="input100" type="text" name="name" placeholder="Enter your name">
          <span class="focus-input100"></span>
        </div>

        <div class="wrap-input100 rs1-wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
          <span class="label-input100">ЕЕлекторонна пошта</span>
          <input class="input100" type="text" name="email" placeholder="Enter your email addess">
          <span class="focus-input100"></span>
        </div>

        <div class="wrap-input100 validate-input" data-validate = "Message is required">
          <span class="label-input100">Повідомлення</span>
          <textarea class="input100" name="message" placeholder="Your message here..."></textarea>
          <span class="focus-input100"></span>
        </div>

        <div class="container-contact100-form-btn">
          <button class="contact100-form-btn">
            <span>
              Submit
              <i class="fa fa-long-arrow-right m-l-7" aria-hidden="true"></i>
            </span>
          </button>
        </div>
      </form>
    </div>
  </div>