<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl() ?>/plugins/animate/animate.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl() ?>/plugins/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl() ?>/plugins/animsition/css/animsition.min.css">
<!--==================================================================/=============================-->
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl() ?>/plugins/select2/select2.min.css">
<!--==================================================================/=============================-->
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl() ?>/plugins/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl() ?>/css/util.css">
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl() ?>/css/main.css">

<script src="<?= $this->baseUrl() ?>/plugins/animsition/js/animsition.min.js"></script>
<script src="<?= $this->baseUrl() ?>/plugins/select2/select2.min.js"></script>
<!--===============================================================================================-->
<script src="<?= $this->baseUrl() ?>/plugins/daterangepicker/moment.min.js"></script>
<script src="<?= $this->baseUrl() ?>/plugins/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
<script src="<?= $this->baseUrl() ?>/plugins/countdowntime/countdowntime.js"></script>

<br><br><br>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>
<div id="dropDownSelect1"></div>
<div class="container">
<div class="row">
  <div class="col-md-2"> </div>
  <div class="col-md-8">
    <h2 class="section-title mb-2 h1 section-heading text-uppercase text-center">Контактна інформація!</h2>
    <hr class="hr">
    <p class="mb-5 text-center">Маєте якісь побажання, або готові почати з нами наступний проект? Це чудово! Передзвоніть нам або надішліть нам електронний лист, і ми зв'яжемося з вами якомога швидше!</p>
    <div class="about-inner-section">                
      <div class="col-lg-6 mr-auto text-center about-inner-column">
        <i class="fa fa-envelope-o fa-2x mb-1 sr-contact"></i>
        <p>feedback@sample.com</p>
      </div>
      <div class="col-lg-6 ml-auto text-center about-right">
        <i class="fa fa-phone fa-2x mb-1 sr-contact"></i>
        <p>123-456-6789</p>
      </div>
    </div>
  </div>
  <div class="clearfix"></div>
  <br>
  <p class="mb-5 text-center">Або скористайтесь нашою формою зворотнього звязку</p>
</div>
</div>

<style type="text/css">
  .contact-form{
    margin-top: 10%;
    width: 40%;
    margin: 0 auto;
    border: 1px solid #007bff;
    height: auto;
    background-color: #17a2b8;
}
.contact-form .col-lg-6, .contact-form .col-md-6{
  padding: 0;
}
.input-group{
  width: 100%;
}
.contact-form h2{
    margin-bottom: 8%;
    text-align: center;
    color: #fff;
}
.contact-form .row div{
  margin-bottom: 5px;
}
.contact-form #send-message{
  bottom: 0;
  background-color: #000080;
  color: #fff;
}
</style>

<div class="container contact-form">
  <div class=""><h2>Форма зворотнього звязку</h2></div>
  
  <div class="row">
    <form method="post">
      <div class="col-lg-6 col-md-6 mb-2">
        <div class="input-group">
          <div class="input-group-addon">
            <div class="input-group-text"><i class="fa fa-user text-info"></i></div>
          </div>
          <input type="text" class="form-control" id="first-name" name="firstName" placeholder="Ім'я" required>
        </div>
      </div>

      <div class="col-lg-6 col-md-6">
        <div class="input-group">
          <div class="input-group-addon">
            <div class="input-group-text"><i class="fa fa-user text-info"></i></div>
          </div>
          <input type="text" class="form-control" id="last-name" name="lastName" placeholder="Прізвище" required>
        </div>
      </div>

      <div class="input-group">
        <div class="input-group-addon">
          <div class="input-group-text"><i class="fa fa-envelope text-info"></i></div>
        </div>
        <input type="text" class="form-control" id="email" name="email" placeholder="Електоронна пошта" required>
      </div>

      <div class="input-group">
        <div class="input-group-addon">
          <div class="input-group-text"><i class="fa fa-comment text-info"></i></div>
        </div>
        <textarea class="form-control" placeholder="Повідомлення" name="message" style="width: 100%; height: 150px;" required></textarea>
      </div>
      <input type="submit" id="send-message" value="Надіслати повідомлення" class="btn btn-block rounded-0 py-2">
    </form>
  </div>
</div>
<br>
<div class="clearfix"></div>
