<?php
	$user = $this->user;
	$form = $this->form;
	foreach ($form->getElements() as $element) {
    $element->setDecorators(array(
    array('ViewHelper'),
));
}
?>
<!--
<div class="container">
  <div class="row" data-ref="container">
    <div class="col-lg-12">
		
		   	
		    <div class="form-group">
		        < ?php echo $form->text->renderLabel() . $form->text->setValue($news[0]["text"])->renderViewHelper() ?>
		    </div>
		    <div class="form-group">
		        <label><b>Додано або змінено:</b></label> < ?= $news[0]["date"] ?>
		    </div>
		    < ?php echo $this->formSubmit('submit', 'Зберегти', array("class" => "btn btn-default")) ?>
		</form>
	</div>
</div>
-->
<div class="container">
    <div class="row" data-ref="container">
        <div class="col-lg-12">
        	<?= var_dump($form->getAction()) ?>
            <form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>" enctype='multipart/form-data'>
                <div class="form-group">
                    <label for="first-name"
                           tag=""
                           class="optional">
                        Ім'я:
                    </label>
                    <div class="form-group">
		        		<?= $form->firstname->setValue($user["firstname"]); ?>
					</div>
                </div>

                <div class="form-group">
                    <label for="last-name"
                           tag=""
                           class="optional">
                        Фамілія:
                    </label>
                    <div class="form-group">
		        		<?= $form->lastname->setValue($user["lastname"]) ?>
		        	</div>
                </div>

                <div class="form-group">
                    <label for="email"
                        tag=""
                        class="optional">
                            Електронна пошта:
                    </label>
					<div class="form-group">
		        		<?= $form->email->setValue($user["email"]) ?>
		        	</div>
                </div>

                <div class="form-group">
                    <label for="phone"
                           tag=""
                           class="optional">
                        Номер телефону:
                    </label>

                    <div class="form-group">
		        		<?= $form->phoneNumber->setValue($user["phoneNumber"]) ?>
		        	</div>
                </div>

                <label for="content"
                       tag=""
                       class="optional">
                    Аватар
                </label>
                <!--
            <div class="radio">
                <label>
                    <input class="form-check-input" type="radio" name="type" id="upload" value="upload">
                    <label for="upload">Вибрати файл з комп'ютера</label>
                </label>
                <div class="upload" style="display: none;">
                    <div id="objects">
                        <div class="form-group" id="add-image1" >
                            <input type="hidden" name="MAX_FILE_SIZE" value="2000000" />
                            <label for="gallery_img" tag="" class="optional">Картинка:</label>
                            <dd>
                                <input type="hidden" name="MAX_FILE_SIZE" value="2097152" id="MAX_FILE_SIZE">
                                <input type="file" name="gallery_img" id="gallery_img" class="form-control">
                            </dd>
                        </div>
                    </div>
                    <p id="add-input" class="btn btn-default">Додати ще одну картинку</p>
                </div>
            </div>
            <div class="radio">
                <label>
                    <input class="form-check-input" type="radio" name="type" id="addurl" value="addurl">
                    <label for="addurl">Вказати URL-адресу</label>
                </label>
                <div class="addurl" style="display: none;">
                    <div class="form-group">
                        <label for="img_url" tag="" class="optional">URL-адреса:</label>
                        <input type="text" name="img_url" id="img_url" value="" class="form-control">
                        <p>Наприклад: https://some_image.com/example.jpg</p>
                    </div>
                </div>
            </div>
        -->
                <div class="addurl">
                    <div class="form-group">
                        <label for="img_url"
                               tag=""
                               class="optional">
                            URL-адреса:
                        </label>

                        <div class="form-group">
		        			<?= $form->profileImg->setValue($user["profileImg"]) ?>
		        		</div>


                        <p>Наприклад: https://some_image.com/example.jpg</p>
                    </div>
                </div>

                <br />
                <div class="pull-right">
                    <input type="submit"
                           name="submit"
                           id="submit"
                           value="Редагувати"
                           class="btn btn-default">

                    <button type="button"
                            class="btn btn-sm text-white btn-secondary">
                        Скасувати
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>