<div class="back">
  <div class="text-center">
    <h1 class="col-md-6 col-md-offset-3">Товари</h1>
  </div>
  <br>
</div>
<div class="back">
  <div class="text-left">
    <ul class="list-inline">
      <li>Сортувати по: </li>
      <li>
        <select id="sort" name="sort">
          <option selected  value ="name">Назві</option>
          <option  value="price">Ціні</option>
        </select>
      </li>
      <li>За: </li>
      <li>
        <select id="type_sort" name="type_sort">
          <option selected  value="asc">Зростанням</option>
          <option  value="desc">Спаданням</option>
        </select>
      </li>
      <li><a id="sorting" class="btn btn-default button-background" href="">Сортувати</a></li>
      <li>hhh</li>
      <li>
        <div class="search-box">
        <form method="POST">
          <input type="text" name="search" placeholder="Пошук"/>
          <a class="search-btn" href="#"><i class="fa fa-search"></i></a>
        </form>
        </div>
      </li>
    </ul>
  </div>
</div>
<div class="container">
  <div class="row">
    <?php
		foreach ($this->products as $key => $value) {
	?>
     <div class="col-lg-3">
        <div class="box">
          <div class="box-gray aligncenter">
            <h3><a class="product" id="product"  product_id="<?= $value->id; ?>" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index')) ?>"><?= $value->name ?></a></h3>
            <div class="icon">
              <i class="fa fa-desktop fa-3x"></i>
            </div>
            <div class="product-item">
              	<?php
              		$url = $this->baseUrl();
    				$img = $url."/".$value->image;
    			?>
    		  <img src="<?= $img ?>" class="img-thumbnail">
              <div class="product-buttons">
                <p>
                  <br><?= $value->minidescription ?><br><br><br>
                  <a href="#"><span style="font: 20px;" class="glyphicon glyphicon-zoom-in"></span></a>
                </p>
              </div>
            </div>
            <div class="buttons-bottom">
              <h3><?= $value->price." грн" ?></h3>
              <a href="" class="btn btn-default btn-block button-background">В корзину</a>
          </div>
        </div>
      </div>
    </div>
  	<?php
  		}
	?>
</div>
<script type="text/javascript">
  function cheked(select) {
    // берём значение из select и что-то с ним делаем
    return select.val();
  };
  $("#sorting").click(function(){
    value_sort = cheked($("#sort"));
    type_sort = cheked($("#type_sort"));
    document.cookie = "sort=" + value_sort;
    document.cookie = "type_sort=" + type_sort; 
    location = "?direction="+type_sort+"&page=1&sort="+value_sort;
  });
  $('body').on('click', 'a#product', function(e) {
    id = $(this).attr("product_id");
    url = $(this).attr("href");
    $.ajax({
      type: "POST",
      url: url,
      data: id,
      success: success,
      dataType: dataType
    });
  });
</script>