<br><br><br>
<div class="container">
	<div class="row">
        <!--
            ["payed"]=> int(0)  ["status"]=> string(23) "На перевірці" } } 
        -->
        <div class="receipt-main col-xs-10 col-sm-10 col-md-6 col-xs-offset-1 col-sm-offset-1 col-md-offset-3">	
			<div class="row">
				<div class="receipt-header receipt-header-mid">
					<div class="col-xs-8 col-sm-8 col-md-8 text-left">
						<div class="receipt-right">
                            <p><b>ПІБ: </b><?= $this->orders[0]["pib"] ?></p>
							<p><b>Електронна пошта: </b><?= $this->orders[0]["email"] ?></p>
                            <p><b>Номер телефону: </b><?= $this->orders[0]["phone"] ?></p>
                            <p><b>Місто: </b><?= $this->orders[0]["address"] ?></p>
                            <br>
                            <p><b>Статус: </b><?= $this->orders[0]["status"] ?></p>
                            <p><b>Статус оплати: </b>
                                <?php 
                                    if($this->orders[0]["payed"] == 1) echo "Оплачено";
                                    else echo "Не оплачено"; 
                                ?></p>
                            <p><b>Спосіб доставки: </b><?= $this->orders[0]["delivery_type"] ?></p>
                            <p><b>Тип оплати: </b><?= $this->orders[0]["pay_type"] ?></p>
                            <p><b>Примітка: </b><?= $this->orders[0]["note"] ?></p>
						</div>
					</div>
				</div>
            </div>
			
            <div>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Опис</th>
                            <th>Кількість</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="col-md-9">Кількість товарів</td>
                            <td class="col-md-3"><i class="fa fa-inr"></i><?= $this->count ?> шт.</td>
                        </tr>
                        <tr>
                            <td class="col-md-9">Загальна вартість</td>
                            <td class="col-md-3"><i class="fa fa-inr"></i><?= number_format($this->sum, 2, ',', ' '); ?> грн.</td>
                        </tr>
                    </tbody>
                </table>
            </div>
			
			<div class="row">
				<div class="receipt-header receipt-header-mid receipt-footer">
					<div class="col-xs-8 col-sm-8 col-md-8 text-left">
						<div class="receipt-right">
							<p><b>Дата замовлення: </b><?= $this->orders[0]["datetime"] ?></p>
						</div>
					</div>
					<div class="col-xs-4 col-sm-4 col-md-4">
						<div class="receipt-left">
						</div>
					</div>
				</div>
            </div>
			<a class="btn btn-danger btn-block" id="<?= $value["id"] ?>" onclick="ajaxQuery('<?php echo $this->url(array('module' => 'default', 'controller'=>'orders','action'=>'cancel', 'order' => "{$value["id"]}"));?>')">Скасувати замовлення</a>   
        </div>    
	</div>
</div>
<script type="text/javascript">
    function ajaxQuery(url){
        $.post(
          url,
          onAjaxSuccess
        );
    }
    function onAjaxSuccess(data)
        {
          location.reload();
        }
</script>