
	<?php
	if(isset($this->errorMessage)){

	            echo $this->errorMessage;

	}?>
	<br>
	<center><h4>Додати новину</h4></center>
	<br>
	<?php

	$form = $this->form;
// Remove <dt> from label generation
foreach ($form->getElements() as $element) {
    $element->getDecorator('label')->setOption('tag', null);
    $form->setAttrib('enctype', 'multipart/form-data');
}
?>
<div class="container">
  <div class="row" data-ref="container">
    <div class="col-lg-12">
		<form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>" enctype='multipart/form-data'>
		   	<div class="form-group">
		        <?php echo $form->title->renderLabel() . $form->title->renderViewHelper() ?>
		    </div>
		    <div class="form-group">
		        <?php echo $form->text->renderLabel() . $form->text->renderViewHelper() ?>
		    </div>
		    
		    <?php echo $this->formSubmit('submit', 'Додати', array("class" => "btn btn-default")) ?>
		</form>
	</div>
</div>