
	<?php
	if(isset($this->errorMessage)){

	            echo $this->errorMessage;

	}
	$news = $this->news[0];
	?>
	<br><br>
	<center><h4><?= $news["title"] ?></h4></center>
	<div class="pull-right" style="padding-right: 100px;">
		<a class="btn btn-primary btn-sm" href="<?php echo $this->url(array('module' => 'admin', 'controller'=>'news','action'=>'edit', 'news' => "{$news["id"]}"));?>"><i class="glyphicon glyphicon-edit"></i></a>
		<a class="btn btn-danger btn-sm" href="<?php echo $this->url(array('module' => 'admin', 'controller'=>'news','action'=>'delete', 'news' => "{$news["id"]}", 'delete' => 1));?>"><i class="glyphicon glyphicon-trash"></i></a>
	</div>
	<br>
<div class="container">
  <div class="row" data-ref="container">
    <div class="col-lg-12">
		   	<div class="form-group">
		        <label>Новина:</label> <?= $news["title"] ?>
		    </div>
		    <div class="form-group">
		        <label>Текст:</label> <?= $news["text"] ?>
		    </div>
		    <div class="form-group">
		        <label><b>Додано або змінено:</b></label> <?= $news["date"] ?>
		    </div>
	</div>
</div>