<script src="<?php echo $this->baseUrl(); ?>/js/mixitup.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/jquery.hideseek.min.js"></script>
<div class="back">
  <div class="text-center">
    <h1 class="col-md-6 col-md-offset-3">Товари</h1>
  </div>
  <br> 
</div>
<style type="text/css">
  .vertical-align {
    display: flex;
    align-items: center;
  }
  .products-menu li{
  }
</style>
<div class="container">
  <div class="row" data-ref="container">
    <div class="col-lg-12">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <ul class="nav navbar-nav text-center vertical-align products-menu">
            <li><a href="#"><b>Усі товари</b></a></li>
            <li>
              <a href="#">
                <img src="<?= $this->baseUrl() ?>/images/new.png"/> <b>Новинки</b>
              </a>
            </li>
            <li>
              <a href="#">
                <img src="<?= $this->baseUrl() ?>/images/best.png"/> <b>Лідери продаж</b>
              </a>
            </li>
            <li>
              <a href="#">
                <img src="<?= $this->baseUrl() ?>/images/sale.png"/> <b>Розпродаж</b>
              </a>
            </li>
            <li>
              <a href="#">
                <img src="<?= $this->baseUrl() ?>/images/promotions.png"/> <b>Акції</b></a>
              </a>
            </li>
            <li>
              <a href="#">
                <img src="<?= $this->baseUrl() ?>/images/gift.png"/> <b>Подарункові сертефікати</b>
              </a>
            </li>
          </ul>
        </div>
      </nav>
      <center>
        <div class="text-left">
          <ul class="list-inline">
            <li>Сортувати по: </li>
            <li>
              <select id="sort" name="sort" class="btn btn-default">
                <option value ="name">Назві</option>
                <option value="price">Ціні</option>
                <option value="type">Типом товару</option>
                <option value="qty">Кількості на складі</option>
              </select>
            </li>
            <li>За: </li>
            <li>
              <select id="type_sort" name="type_sort" class="btn btn-default">
                <option selected value="asc">Зростанням</option>
                <option value="desc">Спаданням</option>
              </select>
            </li>
            <li>
              <div class="range-slider">
                <label class="range-slider-label">Min</label>
                <input name="minSize" class="range-slider-input" type="range" min="0" max="10" value="0" list="sizeLegend"/>
              </div>
            </li>
            <li>
              <div class="range-slider">
                <label class="range-slider-label">Max</label>
                <input name="maxSize" class="range-slider-input" type="range" min="0" max="10" value="10" list="sizeLegend"/>
              </div>
            </li>
            <li><a id="sorting" class="btn btn-default button-background" href="">Сортувати</a></li>
            <li>
            <form method="POST" name="search-form"> 
            <input type="text" name="search" class="search-txt" placeholder="Пошук" data-ref="input-search" data-list=".row" autocomplete="off"/>
          </form>
            </li>
          </ul>
        </div>
      </center>
    </div>
  </div>
</div>
<div class="container">
  <div class="row" data-ref="container">
    <div class="col-lg-2">
      <h2 class="my-4">Категорії:</h2>
      <div class="panel-group" id="accordion">

      <?php
        /* categoriesList
        
          if ($image["product_id"] == $value["id"]) {
            $images[] = $image["image"];
          }
        }
        $img .= $images[0];*/
        $categoriesDistincts = $this->categoriesDistinct;
        $categoriesList = $this->categoriesList;
        foreach ($categoriesDistincts as $categoriesDistinct) {
      ?>
        <!-- 1 панель -->
        <div class="panel panel-default">
          <!-- Заголовок 1 панели -->
          <div class="panel-heading">
            <h4 class="panel-title">
              <div class="checkbox" data-toggle="collapse" data-parent="#accordion" href="#<?= $categoriesDistinct["type"] ?>">
                <label><?= $categoriesDistinct["title"]; ?></label>
              </div>
            </h4>
          </div>
          <div id="<?= $categoriesDistinct["type"] ?>" class="panel-collapse collapse">
            <!-- Содержимое 1 панели -->
            <div class="panel-body">
              <div class="list-group">
                <li class="list-group-item">
                  <div class="checkbox">
                    <label><input type="checkbox" id="mobile_cat">Всі</label>
                  </div>
                </li>
                <?php
                  foreach ($this->categoriesList as $key => $value) {
                    if($categoriesDistinct["type"] == $value["type"]){
                ?>
                <li class="list-group-item">
                  <div class="checkbox">
                    <label><input type="checkbox" class="mobile_cat" value=""><?= $value["brand"]; ?></label>
                  </div>
                </li>
                <?php
                    }
                  }
                ?>
                
              </div>
            </div>
          </div>
        </div>
      <?php
        }
      ?>
      </div>
      </div>
    <div class="col-lg-8">
      <div class="alert right">
        <?php
          $user = Zend_Auth::getInstance();
          if($user->hasIdentity() && $user->getIdentity()->role == "admins"){
        ?>
        <a href="<?php echo $this->url(array( 'module' => 'admin', 'controller' => 'product', 'action' => 'add')) ?>" class="">Додати новий товар</a>
        <?php
          }
        ?>
      </div>
      <div class="clearfix"></div>
      <?php
        foreach ($this->products as $key => $value) {
      ?>
      <div class="col-lg-4" id="<?= $value["id"]; ?>" data-price="<?= $value["price"]; ?>" data-title="<?= $value["name"] ?>">
        <div class="box product-<?= $value["id"]; ?>">
          <div class="box-gray aligncenter">
            <h3><a class="product"  product_id="<?= $value["id"]; ?>" href="<?php echo $this->url(array('controller' => 'products', 'action' => 'show', 'product' => "".$value["id"]."")) ?>"><?= $value["name"] ?></a></h3>
            <div class="product-item">
                <?php
                  $url = $this->baseUrl();
                  $imagesList = $this->images;
                  $images = [];
                  $img_path = $url."/";
                  foreach ($imagesList as $image) {
                    if ($image["product_id"] == $value["id"]) {
                        
                        if($image["upload"] == "local"){
                          $images[] = $img_path.$image["image"];
                        }
                        else{
                          $images[] = $image["image"];
                        }
                    }
                  }
                  $img = $images[0];
                ?>
              <img src="<?= $img ?>" class="img-thumbnail"/>
              <div class="product-buttons">
                <p>
                  <br><?= $value["minidescription"] ?><br><br><br>
                  <a class="image-popup-vertical-fit"  href="<?= $img ?>" title="<?= $value["name"] ?>">
                    <img src="<?= $img ?>" class="img-thumbnail" style="display: none;"/>
                    <span class="glyphicon glyphicon-zoom-in text-center"></span>
                  </a>
                </p>
              </div>
            </div>
            <div class="buttons-bottom">
              <h3><?= $value["price"]." грн." ?></h3>
              <a id="button" href="<?php echo $this->url(array('controller' => 'basket', 'action' => 'add', 'product' => "".$value["id"]."")) ?>" class="btn btn-default btn-block button-background btn-warning"><span class="glyphicon glyphicon-shopping-cart"></span> В корзину</a><br/>
              <a id="button" href="<?php echo $this->url(array('controller' => 'basket', 'action' => 'add', 'product' => "".$value["id"]."")) ?>" class="btn btn-default btn-block button-background btn-warning"><span class="glyphicon glyphicon-heart"></span> В список бажань</a><br/>
              <a id="button" href="#" class="btn btn-default btn-block button-background btn-warning" data-toggle="modal" data-target="#product_view"><i class="fa fa-search"></i> Quick View</a>
            <?php
              $user = Zend_Auth::getInstance();
              if($user->hasIdentity() && $user->getIdentity()->role == "admins"){ 
            ?>
              <a id="button" href="<?php echo $this->url(array( 'module' => 'admin', 'controller' => 'product', 'action' => 'edit', 'product' => "".$value["id"]."")) ?>" class="btn btn-default btn-block button-background btn  btn-info"><span class="glyphicon glyphicon-edit"> Редагувати</span></a>
              <form method="POST" action="<?php echo $this->url(array( 'module' => 'admin', 'controller' => 'product', 'action' => 'delete', 'product' => "".$value["id"]."")) ?>" accept-charset="UTF-8" style="display:inline">
                <a id="button" href="" class="btn btn-default btn-block button-background btn delete-confirm red"  data-toggle="modal" data-target="#confirmDelete" data-title="<?= $value["name"] ?>" data-message="Ви дійсно хочете видалити цей товар?">
                  <span class="glyphicon glyphicon-remove"> Видалити</span>
                </a>
              </form>
            
            <?php
              }
            ?>
            </div>
          </div>
        </div>
      </div>
      <?php
        }
      ?>
    <div class="clearfix"></div>
      <ul class="pager">
        <li>Показати товарів: 
          <select id="show_el" name="show" style="color: black;">
            <option <?php if($this->show == 3) echo "selected"; ?> value ="3">3</option>
            <option <?php if($this->show == 5) echo "selected"; ?> value ="5">5</option>
            <option <?php if($this->show == 6) echo "selected"; ?> value="6">6</option>
            <option <?php if($this->show == 10) echo "selected"; ?> value ="10">10</option>
            <option <?php if($this->show == 25) echo "selected"; ?> value="25">25</option>
            <option <?php if($this->show == 50) echo "selected"; ?> value="50">50</option>
            <option <?php if($this->show == 100) echo "selected"; ?> value="100">100</option>
          </select>
        </li>
        
        <?php
          echo $this->paginationControl($this->products, "sliding", "pagination.phtml");
        ?>
      </ul>

    </div>
    <div class="col-lg-2">
      <h1 class="my-4">Новини</h1>
      <div id="carousel-pager" class="carousel slide " data-ride="carousel" data-interval="2000">
                <!-- Carousel items -->
                <div class="carousel-inner vertical list-group">
                     <?php
                      $lich = 0;
                      foreach ($this->news as $key => $value) {
                    ?>
                      <div class="item <?php if($lich == 0) echo "active"; ?>">
                        <div>
                          <h4 class="list-group-item-heading" style="padding-top: 10px; color: orange;"><?= $value->date; ?></h4>
                          <h4 class="list-group-item-footer"><?= $value->title; ?></h4>
                          <h5 class="list-group-item-text"><?= $value->text; ?></h5>
                          <?php
                            $user = Zend_Auth::getInstance();
                            if($user->hasIdentity() && $user->getIdentity()->role == "admins"){ 
                          ?>
                          <a class="btn btn-primary btn-sm" href="<?php echo $this->url(array( 'module' => 'admin', 'controller' => 'news', 'action' => 'edit', 'news' => "".$value->id."")) ?>"><i class="glyphicon glyphicon-edit"></i></a>
                          <a class="btn  btn-danger btn-sm" href="<?php echo $this->url(array( 'module' => 'admin', 'controller' => 'news', 'action' => 'delete', 'news' => "".$value->id."")) ?>"><i class="glyphicon glyphicon-trash"></i></a>
                          <?php
                            }
                          ?>
                        </div>
                      </div>
                    <?php
                        $lich++;
                      }
                    ?>
                </div>
                
                <!-- Controls -->
                <a class="left carousel-control" href="#carousel-pager" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#carousel-pager" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
    </div>
  </div>
<script type="text/javascript">
//збільшення картинки
$(document).ready(function() {

  $('.image-popup-vertical-fit').magnificPopup({
    type: 'image',
    closeOnContentClick: true,
    mainClass: 'mfp-img-mobile',
    image: {
      verticalFit: true
    }
    
  });

  $('.image-popup-fit-width').magnificPopup({
    type: 'image',
    closeOnContentClick: true,
    image: {
      verticalFit: false
    }
  });

  $('.image-popup-no-margins').magnificPopup({
    type: 'image',
    closeOnContentClick: true,
    closeBtnInside: false,
    fixedContentPos: true,
    mainClass: 'mfp-no-margins mfp-with-zoom', // class to remove default margin from left and right side
    image: {
      verticalFit: true
    },
    zoom: {
      enabled: true,
      duration: 300 // don't foget to change the duration also in CSS
    }
  });
  $('.container').each(function(){
    var highestBox = 0;
    $('.box-gray ', this).each(function(){
      if($(this).height() > highestBox) {
        highestBox = $(this).height();
      }
    });
    $('.box-gray ',this).height(highestBox);
  });
});
/* вибрати всі checkbox-и */
$(document).on("change", "input[type=checkbox]", function() { // По изменению checkbox'а
    if ($(this).attr('class')) {
        var CBgroupID = $(this).attr('class');
    }
    if (($(this).attr('id')) && ($('input[type="checkbox"].' + $(this).attr('id')).length)) { 
        var CBgroupID = $(this).attr('id');
        if (this.checked) {
            $('input[type="checkbox"].' + CBgroupID).attr('checked', 'checked');
            $('input[type="button"][class*="' + CBgroupID + '"]').removeAttr('disabled');
        } else {
            $('input[type="checkbox"].' + CBgroupID).removeAttr('checked');
            $('input[type="button"][class*="' + CBgroupID+'"]').attr('disabled', 'disabled');
        }
    }
    if (!CBgroupID) {
        return;
    }
    if ($('input[type="checkbox"].' + CBgroupID + ':not(:checked)').length) {
        $('input[type="checkbox"]#' + CBgroupID).removeAttr('checked');
    } else {
        $('input[type="checkbox"]#' + CBgroupID).attr('checked', 'checked');
    }
    if ($('input[type="checkbox"].' + CBgroupID+':checked').length) {
        $('input[type="button"][class*="' + CBgroupID + '"]').removeAttr('disabled');
    } else {
        $('input[type="button"][class*="' + CBgroupID + '"]').attr('disabled', 'disabled');
    }
    if ($('input[type="checkbox"].' + CBgroupID + ':checked').length === 1) {
        $('.jToEdit').removeAttr('disabled');
    } else {
        $('.jToEdit').attr('disabled', 'disabled');
    }
    delete CBgroupID;
});

  function cheked(select) {
    // берём значение из select и что-то с ним делаем
    return select.val();
  };
  function get_cookie ( cookie_name )
  {
    var results = document.cookie.match ( '(^|;) ?' + cookie_name + '=([^;]*)(;|$)' );
   
    if ( results )
      return ( unescape ( results[2] ) );
    else
      return null;
  }
  if(document.cookie.match ( '(^|;) ?' + "sort" + '=([^;]*)(;|$)' )){
    $("#sort").value = get_cookie("sort");
    document.getElementById("sort").value = get_cookie("sort");
  }
  if(document.cookie.match ( '(^|;) ?' + "type_sort" + '=([^;]*)(;|$)' )){
    document.getElementById("type_sort").value = get_cookie("type_sort");
  }
  $("#sorting").click(function(){
    value_sort = cheked($("#sort"));
    type_sort = cheked($("#type_sort"));
    document.cookie = "sort=" + value_sort;
    document.cookie = "type_sort=" + type_sort; 
  });
  $('body').on('click', 'a#product', function(e) {
    id = $(this).attr("product_id");
    url = $(this).attr("href");
    $.ajax({
      type: "POST",
      url: url,
      data: id,
      success: success,
      dataType: dataType
    });
  });

  var show = document.querySelector('#show_el');
  show.addEventListener('change', function() {
    document.cookie = "show=" + show.value;
    location.reload();
  });
</script>
<script type="text/javascript">

  var divs = document.getElementsByClassName( 'col-lg-3' );
  //alert(divs.length);
  for( var i = 0; i < divs.length; i++ ) {
      if (divs[i].className!= "") {
          //alert(divs[i].innerHTML);

      }
  }


</script>
<script>
  // In this example, we must bind 'change' event handlers to
  // our <select> elements, then interact with the mixer via
  // its .filter() and .sort() API methods.

  var containerEl = document.querySelector('[data-ref~="container"]');
  //var selectFilter = document.querySelector('.select-filter');
  var sort = document.querySelector('#sort');
  var typeSort = document.querySelector('#type_sort');
  /*
  selectFilter.addEventListener('change', function() {
    var selector = selectFilter.value;
    mixer.filter(selector);
  });
  */
  /* сортування */
  sort.addEventListener('change', function() {
    var mixer = mixitup(containerEl, {
      selectors: {
        target: '[data-' + sort.value +']'
      }
    });
    var order = sort.value + ":" + typeSort.value;
    //mixer.selectors("title");
    mixer.sort(order);
  });
  typeSort.addEventListener('change', function() {
    var mixer = mixitup(containerEl, {
      selectors: {
        target: '[data-' + sort.value +']'
      }
    });
    var order = sort.value + ":" + typeSort.value;
    //mixer.selectors("title");
    mixer.sort(order);
  });

  var inputSearch = document.querySelector('[data-ref="input-search"]');
  var keyupTimeout;

  // Set up a handler to listen for "keyup" events from the search input
  inputSearch.addEventListener('keyup', function() {
    var searchValue;
    if (inputSearch.value.length < 3) {
      // If the input value is less than 3 characters, don't send
      searchValue = '';
    } 
    else {
      searchValue = inputSearch.value./*toLowerCase().*/trim();
      var mixer = mixitup(containerEl, {
        animation: {
          duration: 350
        },
        callbacks: {
          onMixClick: function() {
            // Reset the search if a filter is clicked
            if (this.matches('[data-filter]')) {
              inputSearch.value = '';
            }
          }
        }
      });
    }

    // Very basic throttling to prevent mixer thrashing. Only search
    // once 350ms has passed since the last keyup event
    clearTimeout(keyupTimeout);
    keyupTimeout = setTimeout(function() {
      filterByString(searchValue);
    }, 350);
  });

  /**
  * Filters the mixer using a provided search string, which is matched against
  * the contents of each target's "class" attribute. Any custom data-attribute(s)
  * could also be used.
  *
  * @param  {string} searchValue
  * @return {void}
  */
  function filterByString(searchValue) {
    if (searchValue) {
      // Use an attribute wildcard selector to check for matches
      mixer.filter('[data-title="' + searchValue + '"]');
    } 
    else {
      // If no searchValue, treat as filter('all')
      mixer.filter('all');
    }
  }
</script>

<script type="text/javascript">
/* карусель */
$('.carousel .vertical .item').each(function(){
  var next = $(this).next();
  if (!next.length) {
    next = $(this).siblings(':first');
  }
  next.children(':first-child').clone().appendTo($(this));
  
  for (var i=1;i<2;i++) {
    next=next.next();
    if (!next.length) {
      next = $(this).siblings(':first');
    }
    
    next.children(':first-child').clone().appendTo($(this));
  }
});
</script>


<style type="text/css">
.product_view .modal-dialog{max-width: 800px; width: 100%;}
.pre-cost{text-decoration: line-through; color: #a5a5a5;}
.space-ten{padding: 10px 0;}
</style>

<div class="modal fade product_view" id="product_view">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <a href="#" data-dismiss="modal" class="class pull-right"><span class="glyphicon glyphicon-remove"></span></a>
                <h3 class="modal-title">HTML5 is a markup language</h3>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6 product_img">
                        <img src="http://img.bbystatic.com/BestBuy_US/images/products/5613/5613060_sd.jpg" class="img-responsive">
                    </div>
                    <div class="col-md-6 product_content">
                        <h4>Product Id: <span>51526</span></h4>
                        <div class="rating">
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            (10 reviews)
                        </div>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                        <h3 class="cost"><span class="glyphicon glyphicon-usd"></span> 75.00 <small class="pre-cost"><span class="glyphicon glyphicon-usd"></span> 60.00</small></h3>
                        <div class="row">
                            <div class="col-md-4 col-sm-6 col-xs-12">
                                <select class="form-control" name="select">
                                    <option value="" selected="">Color</option>
                                    <option value="black">Black</option>
                                    <option value="white">White</option>
                                    <option value="gold">Gold</option>
                                    <option value="rose gold">Rose Gold</option>
                                </select>
                            </div>
                            <!-- end col -->
                            <div class="col-md-4 col-sm-6 col-xs-12">
                                <select class="form-control" name="select">
                                    <option value="">Capacity</option>
                                    <option value="">16GB</option>
                                    <option value="">32GB</option>
                                    <option value="">64GB</option>
                                    <option value="">128GB</option>
                                </select>
                            </div>
                            <!-- end col -->
                            <div class="col-md-4 col-sm-12">
                                <select class="form-control" name="select">
                                    <option value="" selected="">QTY</option>
                                    <option value="">1</option>
                                    <option value="">2</option>
                                    <option value="">3</option>
                                </select>
                            </div>
                            <!-- end col -->
                        </div>
                        <div class="space-ten"></div>
                        <div class="btn-ground">
                            <button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-shopping-cart"></span> Add To Cart</button>
                            <button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-heart"></span> Add To Wishlist</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="confirmDelete" role="dialog" aria-labelledby="confirmDeleteLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Delete Parmanently</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure about this ?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Скасувати</button>
        <button type="button" class="btn btn-danger" id="confirm">Видалити</button>
      </div>
    </div>
  </div>
</div>
<!-- Dialog show event handler -->
<script type="text/javascript">
  $('#confirmDelete').on('show.bs.modal', function (e) {
      $message = $(e.relatedTarget).attr('data-message');
      $(this).find('.modal-body p').text($message);
      $title = $(e.relatedTarget).attr('data-title');
      $(this).find('.modal-title').text($title);
 
      // Pass form reference to modal for submission on yes/ok
      var form = $(e.relatedTarget).closest('form');
      $(this).find('.modal-footer #confirm').data('form', form);
  });
 
  <!-- Form confirm (yes/ok) handler, submits form -->
  $('#confirmDelete').find('.modal-footer #confirm').on('click', function(){
      $(this).data('form').submit();
  });
</script>