<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
<style type="text/css">
	@import 'bootstrap-sprockets';
@import "bootstrap/variables";
</style>
<br /><br />
<div id="view-content">
</div>
<?php $product = $this->product[0];
?>
<div class="site-content">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ol class="breadcrumb">
				  <li><a href="<?php echo $this->url(array('module' => 'shop', 'controller' => 'products', 'action' => 'list')) ?>">Головна</a></li>
				  <?php
				  	$type = "";
				  	switch ($product["type"]) {
				  		case 'mobile':
				  			$type = "Мобільні телефони";
				  			break;
				  		case 'notebook':
				  			$type = "Ноутбуки";
				  			break;
				  		case 'notepad':
				  			$type = "Планшети";
				  			break;
				  	}
				  ?>
				  <li><a href="<?php echo $this->url(array('module' => 'shop', 'controller' => 'products', 'action' => 'list', 'type' => $product["type"])) ?>"><?= $type; ?></a></li>
				  <li class="active"><?= $product["name"] ?></li>
				</ol>
				<div class="row">
				    <div class="col-md-3 product_img">

				    	<?php
		                  $url = $this->baseUrl();
		                  $imagesList = $this->images;
		                  $img = "";
			              if($imagesList[0]["upload"] == "local"){
	                        $img .= $url."/";
		                  	$img .= $imagesList[0]["image"];
	                      }
	                      else{
	                        $img .= $imagesList[0]["image"];
	                      }

		                ?>
				        <div class="popup-gallery">
				        	<a href="<?= $img ?>" title="<?= $product["name"] ?>">
								<img src="<?= $img ?>" class="img-responsive" width="200" height="360">
							</a>
							<?php
								foreach ($imagesList as $image) {
									$img = "";
						            if($image["upload"] == "local"){
				                  	    $img .= $url."/";
					                  	$img .= $image["image"];
				                    }
				                    else{
				                        $img .= $image["image"];
				                    }
			                    	?>
			                <a href="<?= $img ?>" title="<?= $product["name"] ?>">
								<img src="<?= $img ?>" class="img-responsive" height="85" width="65">
							</a>
			                    	<?php
			                  	}
			                ?>
						</div>
				    </div>
				    <div class="col-md-9 product_content">
				        <h3><?= $product["name"] ?></h3>
				        <div class="rating">
				        	<span class="glyphicon glyphicon-star"></span>
				            <span class="glyphicon glyphicon-star"></span>
				            <span class="glyphicon glyphicon-star"></span>
				            <span class="glyphicon glyphicon-star"></span>
				            <span class="glyphicon glyphicon-star"></span>
				            (10 reviews)
				        </div>
				       	<p><h4>Короткий опис:</h4><?= $product["minidescription"] ?></p>
				       	<p><h4>Короткі характеристики:</h4><?= $product["minicharacteristic"] ?></p>
				        <h3 class="cost"><?= $product["price"] ?> грн.</h3>
				        <div class="row">
				            <div class="col-md-4 col-sm-6 col-xs-12">
				              	<select class="form-control" name="select">
				                    <option value="" selected="">Color</option>
				                    <option value="black">Black</option>
				                    <option value="white">White</option>
				                    <option value="gold">Gold</option>
				                	<option value="rose gold">Rose Gold</option>
				                </select>
				            </div>
				            <!-- end col -->
				            <div class="col-md-4 col-sm-6 col-xs-12">
				                <select class="form-control" name="select">
				                    <option value="">Capacity</option>
				                    <option value="">16GB</option>
				                   	<option value="">32GB</option>
				                    <option value="">64GB</option>
				                    <option value="">128GB</option>
				                </select>
				            </div>
				            <!-- end col -->
				        </div>
				        <div class="clear"></div>
				        <div class="space-ten"></div>
				        <div class="btn-ground">
				       		<button type="button" class="btn btn-primary primary"><span class="glyphicon glyphicon-shopping-cart"></span>Додати в корзину</button>
				            <button type="button" class="btn btn-primary primary"><span class="glyphicon glyphicon-heart"></span>Додати в список бажань</button>
				        </div>
				        <div class="clear"></div>
				        <ul class="nav nav-tabs">
						  <li class="active"><a data-toggle="tab" href="#description">Опис</a></li>
						  <li><a data-toggle="tab" href="#characterstic">Характеристики</a></li>
						  <li><a data-toggle="tab" href="#reviews">Відгуки</a></li>
						</ul>
						<div class="tab-content">
						  	<div id="description" class="tab-pane fade in active">
						    	<p><?= $product["description"] ?></p>
						  	</div>
						  	<div id="characterstic" class="tab-pane fade">
						    	<p><?= $product["characterstic"] ?></p>
						  	</div>
						  	<div id="reviews" class="tab-pane fade">
								<div class="woocommerce-Tabs-panel woocommerce-Tabs-panel--reviews panel entry-content wc-tab" id="tab-reviews" role="tabpanel" aria-labelledby="tab-title-reviews">
									<div id="reviews" class="woocommerce-Reviews">
										<div id="comments">
											<h2 class="woocommerce-Reviews-title">Відгуки</h2>
										</div>
										<div id="review_form_wrapper">
											<div id="review_form">
												<div id="respond" class="comment-respond">
													<?php
														if(count($this->reviews) > 1){
															echo "<ul class='list-group'>";
															foreach ($this->reviews as $review) {
																$bad_review = "";
																$good_review = "";
																if($review["good_review"] != ""){
																	$good_review = "<h4><span class='text-success'>+</span> {$review["good_review"]}</h4>";
																}
																if($review["bad_review"] != ""){
																	$bad_review = "<h4><span class='text-danger'>-</span> {$review["bad_review"]}</h4>";
																}
									                    	?>
									                <li class="list-group-item">
										               	<div class="review-block">
										               		<?= $review["date"]; ?>
															<h3><?= $review["author"]; ?></h3>
															<?= $good_review; ?>
															<?= $bad_review; ?>
															<p style="font-size: 20px;"><?= $review["comment"] ?></p>
														</div>
													</li>
									                    	<?php
									                    	}
									                    	echo "</ul>";
									                  	}
									                  	else if(count($this->reviews) == 1){
									                  		echo "<ul class='list-group'>";
									                  			$review = $this->reviews[0];
																$bad_review = "";
																$good_review = "";
																if($review["good_review"] != ""){
																	$good_review = "<h4><span class='text-success'>+</span> {$review["good_review"]}</h4>";
																}
																if($review["bad_review"] != ""){
																	$bad_review = "<h4><span class='text-danger'>-</span> {$review["bad_review"]}</h4>";
																}
									                    	?>
									                <li class="list-group-item">
										               	<div class="review-block">
										               		<?= $review["date"]; ?>
															<h3><?= $review["author"]; ?></h3>
															<?= $good_review; ?>
															<?= $bad_review; ?>
															<p style="font-size: 20px;"><?= $review["comment"] ?></p>
														</div>
													</li>
									                    	<?php
									                    	echo "</ul>";
									                  	}
									                  	else if(count($this->products) < 1){
															echo "<center><h4>Відгуків до даного товару поки що немає </h4></center><br>Будьте першим хто напише відгук";
														}
									                ?>
									                <br><br>
													<span id="reply-title" class="comment-reply-title">
														<h2>Написати відгук</h2>
														<small><a rel="nofollow" id="cancel-comment-reply-link" href="/tyche/product/black-top/#respond" style="display:none;">Cancel reply</a></small>
													</span>	
													<?php
														if(isset($this->errorMessage)){
															echo $this->errorMessage;

														}
														?>
														<br>
														<center><h4>Додати товар</h4></center>
														<br>
														<?php

														$form = $this->form;
														// Remove <dt> from label generation
														foreach ($form->getElements() as $element) {
														    $element->getDecorator('label')->setOption('tag', null);
														}
													?>		
													<form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
														<div class="form-group">
													        <?php echo $form->product_id->setValue($product["id"])->renderViewHelper() ?>
													    </div>
														<div class="form-group">
															<?php
													            $user = Zend_Auth::getInstance();
													            $author = "Incognito";
													            if ( $user->hasIdentity()) $author = $user->getIdentity()->firstname." ".$user->getIdentity()->lastname; 
													        ?>
													        <?php echo $form->author->renderLabel() . $form->author->setValue($author)->renderViewHelper() ?>
													    </div>
													    <div class="form-group">
													    	<div id="star"></div>
												        	<?php echo $form->mark->renderViewHelper() ?>
													    </div>
													    <div class="form-group">
												        	<?php echo $form->good_review->renderLabel() . $form->good_review->renderViewHelper() ?>
													    </div>
													    <div class="form-group">
												        	<?php echo $form->bad_review->renderLabel() . $form->bad_review->renderViewHelper() ?>
													    </div>
													    <div class="form-group">
												        	<?php echo $form->comment->renderLabel() . $form->comment->renderViewHelper() ?>
													    </div>
													    <?php echo $this->formSubmit('submit', 'Зберегти'/*, 'class' => "btn btn-primary btn-md"*/) ?>
													    <?php /*echo $this->formSubmit('reset', 'Очистити'/*, 'class' => "btn btn-default btn-md")*/ ?>
													    <script type="text/javascript">
													    		$('#star').raty({
																  cancel     : true,
																  target     : '#mark',
																  targetKeep : true,
																  targetType : 'number',
																  half       : true,
																  precision  : true,
																  size       : 24,
																  starHalf   : '<?php echo $this->baseUrl(); ?>/plugins/jquery-raty/images/star-half.png',
																  starOff    : '<?php echo $this->baseUrl(); ?>/plugins/jquery-raty/images/star-off.png',
																  starOn     : '<?php echo $this->baseUrl(); ?>/plugins/jquery-raty/images/star-on.png',
																  cancelOff    : '<?php echo $this->baseUrl(); ?>/plugins/jquery-raty/images/cancel-off.png',
																  cancelOn     : '<?php echo $this->baseUrl(); ?>/plugins/jquery-raty/images/cancel-on.png'
																  //
																});
													    	</script>
													</form>
												</div>
											</div>
										</div>
									<div class="clear"></div>
								</div>
							</div>
						  </div>
						</div>
				    </div>
				</div>

<!--
				<div class="product_meta">
					<span class="posted_in">Categories: <a href="https://colorlib.com/tyche/product-category/tops/" rel="tag">Tops</a>, <a href="https://colorlib.com/tyche/product-category/trends/" rel="tag">Trends</a></span>
				</div>
				<div class="woocommerce-tabs wc-tabs-wrapper">
					<ul class="tabs wc-tabs tyche-wc-tabs" role="tablist">
						<li class="description_tab" id="tab-title-description" role="tab" aria-controls="tab-description">
							<a href="#tab-description">Description</a>
						</li>
						<li class="reviews_tab" id="tab-title-reviews" role="tab" aria-controls="tab-reviews">
							<a href="#tab-reviews">Reviews (0)</a>
						</li>
					</ul>
					
				</div>
-->
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
$(document).ready(function() {
	$('.popup-gallery').magnificPopup({
		delegate: 'a',
		type: 'image',
		tLoading: 'Loading image #%curr%...',
		mainClass: 'mfp-img-mobile',
		gallery: {
			enabled: true,
			navigateByImgClick: true,
			preload: [0,1] // Will preload 0 - before current, and 1 after the current image
		},
		image: {
			tError: '<a href="%url%">The image #%curr%</a> could not be loaded.',
			titleSrc: function(item) {
				return item.el.attr('title');
			}
		}
	});
});
</script>

<?= var_dump($this->data) ?>