<br /><br />
<center>
<div id="view-content">
	<h2>Ім`я - <b><?php echo $this->user->firstname; ?></b></h2></br>
	<h2>Фамілія - <b><?php echo $this->user->lastname; ?></b></h2></br>
	<h2>Емейл - <b><?php echo $this->user->email; ?></b></h2></br>
	<h2>Місце проживання - <b><?php echo $this->user->city; ?></b></h2></br> 
	<a href="<?php echo $this->url(array('controller'=>'customer','action'=>'update'));?>">Змінити дані</a>
</div>
</center>