<?= $this->doctype(); ?>
<html>
  <head>
    <?= $this->headMeta(); ?>
    <?= $this->headTitle(); ?>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="shortcut icon" type="image/gif/png" href="<?php echo $this->baseUrl(); ?>/images/logo.png" />
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/styles.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/js.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>
<div class="navbar-fixed-top text-center navbar-inverse" >
  <span id="show">Показати меню</span>
</div>
  <nav class="navbar navbar-inverse navbar-fixed-top" id="top-menu" role="navigation" >
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle Navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><img src="<?php echo $this->baseUrl(); ?>/images/logo.png"/></li>
          <li>
            <a style="color: white;" href="<?php echo $this->url(array('module' => 'shop', 'controller' => 'products', 'action' => 'list')) ?>">Головна</a>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-center">
          <li class="text-center center-block"><a style="color: white;" id="hide">Приховати меню</a></li>
        </ul>
          <?php
            $user = Zend_Auth::getInstance();
            if ( $user->hasIdentity()) : $customer = $user->getIdentity()->firstname." ".$user->getIdentity()->lastname; ?>
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a  href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                <span class="glyphicon glyphicon-user vidstupi"></span><?php echo $customer ?> <span class="caret"></span>
                <ul class="dropdown-menu">
                  <li>
                    <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'customer', 'action' => 'index')) ?>">Панель користувача</a>
                  </li>
                  <li>
                    <a href="<?php echo $this->url(array('module' => 'default', 'controller'=>'customer','action'=>'mydata'));?>">Особисті дані</a>
                  </li>
                </ul>
              </a>
            </li>
            <li>
              <a style="color: white;" href="<?php echo $this->url(array('module' => 'default', 'controller'=>'customer','action'=>'logout'));?>"><span class="glyphicon glyphicon-log-out vidstupi"></span>Вийти</a>
            </li>
                <?php else: ?>
          <ul class="nav navbar-nav navbar-right">  
            <li><a style="color: white;" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'customer', 'action' => 'signup')) ?>"><span class="glyphicon glyphicon-user vidstupi"></span>Зареєструватись</a></li>
            <li><a style="color: white;" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'customer', 'action' => 'login')) ?>"><span class="glyphicon glyphicon-log-in vidstupi"></span>Ввійти</a></li>
              <?php endif;?>
          </ul> 
        </ul>                  
      </div>
    </div>
  </nav>
<br>
<?php echo $this->layout()->content; ?>
<footer class="text-center navbar navbar-bottom">
  <p class="pull-right"><a class="vidstupi" href="#" id="up"><span class="glyphicon glyphicon-arrow-up vidstupi"></span>Наверх</a></p>
  <p>&copy; 2018 Lakatosh Vitaliy. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
</footer>
</footer>
<script type="text/javascript">
jQuery(function(f){
    var element1 = f('#top-menu');
    var element2 = f('#show');
    var element3 = f('#up');
    f(window).scroll(function(){
        document.getElementById("top-menu").style.display = "none";
        element1['fade'+ (f(this).scrollTop() < 100 ? 'In': 'Out')](100);
        element2['fade'+ (f(this).scrollTop() > 100 ? 'In': 'Out')](100);
        element3['fade'+ (f(this).scrollTop() > 100 ? 'In': 'Out')](100);         
    });
});   

  $( "#show" ).on( "click", function() {
    document.getElementById("top-menu").style.display = "block";
    document.getElementById("#show").style.display = "none";
  });
  $( "#hide" ).on( "click", function() {
    document.getElementById("show").style.display = "block";
    document.getElementById("top-menu").style.display = "none";
  });
</script>
</html>