<?= $this->doctype(); ?>
<html>
  <head>
    <?= $this->headMeta(); ?>
    <?= $this->headTitle(); ?>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="shortcut icon" type="image/gif/png" href="<?php echo $this->baseUrl(); ?>/images/logo.png" />
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/styles.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/js.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/plugins/magnific-popup/magnific-popup.css">
    <script src="<?php echo $this->baseUrl(); ?>/plugins/magnific-popup/magnific-popup.js"></script>
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/plugins/jquery-raty/jquery.raty.css">
    <script src="<?php echo $this->baseUrl(); ?>/plugins/jquery-raty/jquery.raty.js"></script>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/plugins/fancybox/jquery.fancybox.css"/>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/plugins/fancybox/jquery.fancybox.js"></script>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
    <style type="text/css">
      @import 'bootstrap-sprockets';
    @import "bootstrap/variables";
    </style>
    ?>
    <?php //$this->dojo()->enable(); ?>
  </head>
<div class="navbar-fixed-top text-center navbar-inverse" >
  <span id="show">Показати меню</span>
</div>
  <nav class="navbar navbar-inverse navbar-fixed-top" id="top-menu" role="navigation" >
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle Navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><img src="<?php echo $this->baseUrl(); ?>/images/logo.png"/></li>
          <li>
            <a style="color: white;" href="<?php echo $this->url(array('module' => 'shop', 'controller' => 'products', 'action' => 'list')) ?>">Головна</a>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-center">
          <li class="text-center center-block"><a style="color: white;" id="hide">Приховати меню</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li>
              <?php
              $cartsTbl = new Shop_Model_DbTable_Cart();
              $carts = $cartsTbl->getCart("cart_ip", "{$_SERVER['REMOTE_ADDR']}");
              $count = 0;
              $sum = 0;
              if(count($carts) > 1){
                foreach ($carts as $cart) {
                  $sum += $cart["cart_price"] * $cart["cart_count"];
                  $count += $cart["cart_count"];
                }
              }
              else{
                $sum += $carts[0]["cart_price"] * $carts[0]["cart_count"];
                $count += $carts[0]["cart_count"];
              }
              //echo substr($sum, 0, 1); // 2
              //echo substr($sum, -1); // 8
              ?>
              <a style="color: white;" href="<?php echo $this->url(array('module' => 'shop', 'controller'=>'basket','action'=>'show'));?>"><span class="glyphicon glyphicon-shopping-cart"></span> Корзина [<b><?= $count; ?> товари</b> на суму <b><?= number_format($sum, 2, ',', ' ');; ?> грн.</b>]</a>
            </li>
          <?php
            $user = Zend_Auth::getInstance();
            if ( $user->hasIdentity()) : $customer = $user->getIdentity()->firstname." ".$user->getIdentity()->lastname; ?>
            <li class="dropdown">
              <a style="color: white;" href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                <span class="glyphicon glyphicon-user vidstupi"></span><?php echo $customer ?> <span class="caret"></span>
                <ul class="dropdown-menu">
                  <li>
                    <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'customer', 'action' => 'index')) ?>">Панель користувача</a>
                  </li>
                  <li>
                    <a href="<?php echo $this->url(array('module' => 'default', 'controller'=>'customer','action'=>'mydata'));?>">Особисті дані</a>
                  </li>
                </ul>
              </a>
            </li>
            <li>
              <a style="color: white;" href="<?php echo $this->url(array('module' => 'default', 'controller'=>'customer','action'=>'logout'));?>"><span class="glyphicon glyphicon-log-out vidstupi"></span>Вийти</a>
            </li>
                <?php else: ?> 
            <li><a style="color: white;" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'customer', 'action' => 'signup')) ?>"><span class="glyphicon glyphicon-user vidstupi"></span>Зареєструватись</a></li>
            <li><a style="color: white;" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'customer', 'action' => 'login')) ?>"><span class="glyphicon glyphicon-log-in vidstupi"></span>Ввійти</a></li>
              <?php endif;?>
          </ul> 
        </ul>                  
      </div>
    </div>
  </nav>
<br><br><br>
<?php
  $user = Zend_Auth::getInstance();
  if ( $user->hasIdentity() && $user->getIdentity()->role == "admins"){ 
?>
<div class="side-menu">
  <nav class="navbar navbar-default" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <div class="brand-wrapper">
        <!-- Hamburger -->
        <button type="button" class="navbar-toggle">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
    </div>
    <!-- Main Menu -->
    <div class="side-menu-container">
      <ul class="nav navbar-nav">

        <!-- Dropdown-->
        <li class="panel panel-default" id="dropdown">
          <a data-toggle="collapse" href="#dropdown-lvl1">
            <span class="glyphicon glyphicon-user"></span> Товари <span class="caret"></span>
          </a>

          <!-- Dropdown level 1 -->
          <div id="dropdown-lvl1" class="panel-collapse collapse">
            <div class="panel-body">
              <ul class="nav navbar-nav">
                <li><a href="#">Проглянути усі товари</a></li>
                <li><a href="#">Додати новий товар</a></li>

                <!-- Dropdown level 2 -->
                <li class="panel panel-default" id="dropdown">
                  <a data-toggle="collapse" href="#dropdown-sublvl1">
                    <span class="glyphicon glyphicon-off"></span> Sub Level <span class="caret"></span>
                  </a>
                  <div id="dropdown-sublvl1" class="panel-collapse collapse">
                    <div class="panel-body">
                      <ul class="nav navbar-nav">
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                      </ul>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </div>
          <a data-toggle="collapse" href="#dropdown-lvl2">
            <span class="glyphicon glyphicon-user"></span> Новини <span class="caret"></span>
          </a>

          <!-- Dropdown level 1 -->
          <div id="dropdown-lvl2" class="panel-collapse collapse">
            <div class="panel-body">
              <ul class="nav navbar-nav">
                <li><a href="#">Проглянути усі новини</a></li>
                <li><a href="#">Додати нову новину</a></li>

                <!-- Dropdown level 2 -->
                <li class="panel panel-default" id="dropdown">
                  <a data-toggle="collapse" href="#dropdown-sublvl2">
                    <span class="glyphicon glyphicon-off"></span> Sub Level <span class="caret"></span>
                  </a>
                  <div id="dropdown-sublvl2" class="panel-collapse collapse">
                    <div class="panel-body">
                      <ul class="nav navbar-nav">
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                      </ul>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </li>

        <li><a href="#"><span class="glyphicon glyphicon-signal"></span> Link</a></li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>
</div>
<?php 
  }
  echo $this->layout()->content; ?>
<footer class="text-center navbar navbar-bottom">
  <p class="pull-right"><a class="vidstupi" href="#" id="up"><span class="glyphicon glyphicon-arrow-up vidstupi"></span>Наверх</a></p>
  <p>&copy; 2018 Lakatosh Vitaliy. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
</footer>
</footer>
<script type="text/javascript">
jQuery(function(f){
    var element1 = f('#top-menu');
    var element2 = f('#show');
    var element3 = f('#up');
    f(window).scroll(function(){
        document.getElementById("top-menu").style.display = "none";
        element1['fade'+ (f(this).scrollTop() < 100 ? 'In': 'Out')](100);
        element2['fade'+ (f(this).scrollTop() > 100 ? 'In': 'Out')](100);
        element3['fade'+ (f(this).scrollTop() > 100 ? 'In': 'Out')](100);         
    });
});   

  $( "#show" ).on( "click", function() {
    document.getElementById("top-menu").style.display = "block";
    document.getElementById("#show").style.display = "none";
  });
  $( "#hide" ).on( "click", function() {
    document.getElementById("show").style.display = "block";
    document.getElementById("top-menu").style.display = "none";
  });
</script>
</html>