<br><br>
<div class="container">
<table id="cart" class="table table-hover table-condensed">
    	<thead>
			<tr>
				<th style="width:25%">ПІБ</th>
				<th style="width:30%">Електронна пошта</th>
				<th style="width:30%">Адреса</th>
				<th style="width: 5%">Статус</th>
				<th style="width:10%">Роль</th>
			</tr>
		</thead>
		<tbody>
			<?php

				if(count($this->users) > 1){

	        		foreach ($this->users as $key => $value) {
	      		?>
				<tr>
					<td data-th="Product">
							<div class="col-sm-10">
		                        <div class="media">
		                            <div class="media-body">
		                                <h4 class="media-heading">
		                                	<a class="product"  product_id="<?= $value["id"]; ?>" href="<?php echo $this->url(array('module' => 'admin', 'controller'=>'uderd','action'=>'show', 'user' => "{$value["id"]}"));?>"><?= $value["firstname"]." ".$value["lastname"] ?></a>
		                                </h4>
		                            </div>
								</div>
							</div>
					</td>
					<td><?= $value["email"] ?></td>
					<td><?= $value["city"] ?></td>
					<td><?= $value["status"] == 1 ? "Онлайн" : "Офлайн" ?></td>
					<td><?= $value["role"] ?></td>
					<td class="actions" data-th="">
						<a href="" class="btn btn-danger btn-sm"  data-toggle="modal" data-target="#confirmDelete" data-title="<?= $value["firstname"]." ".$value["lastname"] ?>" id="<?= $value["id"] ?>" action="ajaxQuery(this.value, 'users/delete/user/')" data-message="Ви дійсно хочете видалити цього користувача?"><i class="glyphicon glyphicon-trash"></i></a>						
					</td>
				</tr>
				<?php
					}
					?>

		</tbody>
	</table>
	<!--
	<ul class="pager">
	        <li>Показати товарів: 
	          <select id="show_el" name="show" style="color: black;">
	            <option < ?php if($this->show == 5) echo "selected"; ?> value ="5">5</option>
	            <option < ?php if($this->show == 10) echo "selected"; ?> value ="10">10</option>
	            <option < ?php if($this->show == 25) echo "selected"; ?> value="25">25</option>
	            <option < ?php if($this->show == 50) echo "selected"; ?> value="50">50</option>
	            <option < ?php if($this->show == 100) echo "selected"; ?> value="100">100</option>
	          </select>
	        </li>
	        
	        < php
	          echo $this->paginationControl($this->news, "sliding", "pagination.phtml");
	        ?>
	      </ul>
	     -->
</div>
					<?php
				}
				else if(count($this->users) == 1){
						$value = $this->users[0];
	      		?>
				<tr>
					<td data-th="Product">
							<div class="col-sm-10">
		                        <div class="media">
		                            <div class="media-body">
		                                <h4 class="media-heading">
		                                	<a class="product"  product_id="<?= $value["id"]; ?>" href="<?php echo $this->url(array('module' => 'shop', 'controller'=>'products','action'=>'show', 'product' => "{$value["id"]}"));?>"><?= $value["firstname"]." ".$value["lastname"] ?></a>
		                                </h4>
		                            </div>
								</div>
							</div>
					</td>
					<td><?= $value["email"] ?></td>
					<td><?= $value["city"] ?></td>
					<td><?= $value["role"] ?></td>
					<td class="actions" data-th="">
						<a id="button" href="" class="btn btn-danger btn-sm"  data-toggle="modal" data-target="#confirmDelete" data-title="<?= $value["firstname"]." ".$value["lastname"] ?>" data-message="Ви дійсно хочете видалити цього користувача?"><i class="glyphicon glyphicon-trash"></i></a>							
					</td>
				</tr>
		</tbody>
		<tfoot>
		</tfoot>
	</table>
</div>
<?php
	}
?>
<div class="modal fade" id="confirmDelete" role="dialog" aria-labelledby="confirmDeleteLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Delete Parmanently</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure about this ?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Скасувати</button>
        <button type="button" class="btn btn-danger" id="confirm" value="" onclick="">Видалити</button>
      </div>
    </div>
  </div>
</div>
<!-- Dialog show event handler -->
<script type="text/javascript">
  $('#confirmDelete').on('show.bs.modal', function (e) {
      $message = $(e.relatedTarget).attr('data-message');
      $(this).find('.modal-body p').text($message);

      $title = $(e.relatedTarget).attr('data-title');
      $(this).find('.modal-title').text($title);

      $id = $(e.relatedTarget).attr('id');
      $(this).find('.modal-footer #confirm').attr("value", $id);

      $onclick = $(e.relatedTarget).attr('action');
      $(this).find('.modal-footer #confirm').attr("onclick", $onclick);
      // Pass form reference to modal for submission on yes/ok
      var form = $(e.relatedTarget).closest('form');
      $(this).find('.modal-footer #confirm').data('form', form);
  });
 
  <!-- Form confirm (yes/ok) handler, submits form -->
  $('#confirmDelete').find('.modal-footer #confirm').on('click', function(){
      $(this).data('form').submit();
  });
</script>
<script type="text/javascript">

	function ajaxQuery(id, url){
		$.post(
		  url + id,
		  onAjaxSuccess
		);

	}
	function onAjaxSuccess(data)
		{
		  location.reload();
		}
</script>