
<br><br>
<div class="container">
	<table id="cart" class="table table-hover table-condensed">
    	<thead>
			<tr>
				<th style="width:50%">Товар</th>
				<th style="width:10%">Ціна</th>
				<th style="width:8%">Кількість</th>
				<th style="width:22%" class="text-center">Вартість</th>
				<th style="width:10%"></th>
			</tr>
		</thead>
		<tbody>
			<?php
        		foreach ($this->products as $key => $value) {
        			$cartsTbl = new Shop_Model_DbTable_Cart();
              		$cart = $cartsTbl->getCart("cart_id_products", "{$value[0]["id"]}");
      		?>
			<tr>
				<td data-th="Product">
					<div class="row">
						<?php
		                  $url = $this->baseUrl();
		                  $imagesList = $this->images;
		                  $images = [];
		                  $img_path = $url."/";
		                  foreach ($imagesList as $image) {
		                    if ($image[0]["product_id"] == $value[0]["id"]) {
		                        
		                        if($image[0]["upload"] == "local"){
		                          $images[] = $img_path.$image[0]["image"];
		                        }
		                        else{
		                          $images[] = $image[0]["image"];
		                        }
		                    }
		                  }
		                  $img = $images[0]; 
		                ?>
						<div class="col-sm-2 hidden-xs"><img src="<?= $img ?>" alt="..." width="100" height="125" class="img-responsive"/></div>
						<div class="col-sm-10">
							<h4 class="nomargin"><?= $value[0]["name"] ?></h4>
						</div>
					</div>
				</td>
				<td data-th="Price"><?= $cart[0]["cart_price"] ?></td>
				<td data-th="Quantity">
					<input type="number" class="form-control text-center" value="<?= $cart[0]["cart_count"] ?>">
				</td>
				<td data-th="Subtotal" class="text-center"><?= number_format($cart[0]["cart_price"] * $cart[0]["cart_count"], 2, ',', ' '); ?></td>
				<td class="actions" data-th="">
					<button class="btn btn-info btn-sm"><i class="glyphicon glyphicon-refresh"></i></button>
					<button class="btn btn-danger btn-sm"><i class="glyphicon glyphicon-trash"></i></button>								
				</td>
			</tr>
			<?php
				}
			?>
		</tbody>
		<tfoot>
			<tr class="visible-xs">
				<td class="text-center"><b><?= $this->count; ?> товари</b> на суму <b><?= number_format($this->sum, 2, ',', ' ');; ?> грн.</b></td>
			</tr>
			<tr>
				<td><a href="<?php echo $this->url(array('module' => 'shop', 'controller' => 'products', 'action' => 'list')) ?>" class="btn btn-warning"><i class="glyphicon glyphicon-chevron-left fa fa-angle-left"></i> Продовжити вибирати товари</a></td>
				<td colspan="2" class="hidden-xs"></td>
				<td class="hidden-xs text-center"><b><?= $this->count; ?> товари</b> на суму <b><?= number_format($this->sum, 2, ',', ' ');; ?> грн.</b></td>
				<td><a href="#" class="btn btn-success btn-block">Оформити замовлення <i class="fa fa-angle-right glyphicon glyphicon-chevron-right"></i></a></td>
			</tr>
		</tfoot>
	</table>
</div>