<br><br>
<div class="container">
<h2>Відгуки до товара #<?= $this->id ?> </h2>
<table id="cart" class="table table-hover table-condensed">
    	<thead>
			<tr>
				<th style="width:5%">ID</th>
				<th style="width:20%">Дата</th>
				<th style="width:10%">Автор</th>
				<th style="width:20%">Хороший відгук</th>
				<th style="width:20%">Поганий відгук</th>
				<th style="width:15%">Коментар</th>
				<th style="width:5%">Оцінка</th>
				<th style="width:5%"></th>
			</tr>
		</thead>
		<tbody>
			<?php

				if(count($this->reviews) > 1){

	        		foreach ($this->reviews as $key => $value) {
	      		?>
				<tr>
					<td>
						<div class="col-sm-10">
		                    <div class="media">
		                        <div class="media-body">
		                            <h4 class="media-heading">
		                               	<a class="product"  product_id="<?= $value["product_id"]; ?>" href="<?php echo $this->url(array('module' => 'admin', 'controller'=>'reviews','action'=>'show', 'review' => "{$value["id"]}"));?>"><?= $value["id"] ?></a>
		                            </h4>
		                        </div>
							</div>
						</div>
					</td>
					<td><?= $value["date"] ?></td>
					<td><?= $value["author"] ?></td>
					<td><?= $value["good_review"] ?></td>
					<td><?= $value["bad_review"] ?></td>
					<td><?= $value["comment"] ?></td>
					<td><?= $value["mark"] ?></td>
					<td>
						<?php
							if($value["moderal"] == 1){
						?>
						<a class="btn btn-default btn-sm" title="Приховати коментар" id="<?= $value["id"] ?>" onclick="ajaxQuery(this.id, '../../../../makevisible/moderal/0/review/')"><i class="glyphicon glyphicon-eye-close"></i></a>
						<?php
							}
							else{
						?>
						<a class="btn btn-success btn-sm" title="Зробити доступним для усіх" id="<?= $value["id"] ?>" onclick="ajaxQuery(this.id, '../../../../makevisible/moderal/1/review/')"><i class="glyphicon glyphicon-eye-open"></i></a>
						<?php } ?>
						<a class="btn btn-danger btn-sm" id="<?= $value["id"] ?>" onclick="ajaxQuery(this.id, '../../../../delete/review/')"><i class="glyphicon glyphicon-trash"></i></a>
					</td>
				</tr>
				<?php
					}
					?>
		</tbody>
	</table>
	<!--
	<ul class="pager">
	        <li>Показати товарів: 
	          <select id="show_el" name="show" style="color: black;">
	            <option < ?php if($this->show == 5) echo "selected"; ?> value ="5">5</option>
	            <option < ?php if($this->show == 10) echo "selected"; ?> value ="10">10</option>
	            <option < ?php if($this->show == 25) echo "selected"; ?> value="25">25</option>
	            <option < ?php if($this->show == 50) echo "selected"; ?> value="50">50</option>
	            <option < ?php if($this->show == 100) echo "selected"; ?> value="100">100</option>
	          </select>
	        </li>
	        
	        < php
	          echo $this->paginationControl($this->news, "sliding", "pagination.phtml");
	        ?>
	      </ul>
	     -->
</div>
					<?php
				}
				else if(count($this->news) == 1){
						$news = $this->news[0];
	      		?>
				<tr>
					<td data-th="Product">
						<div class="row">
							<div class="col-sm-10">
		                        <div class="media">
		                            <div class="media-body">
		                                <h4 class="media-heading"><a href="#"><a class="news"  product_id="<?= $news["id"]; ?>" href="<?php echo $this->url(array('controller' => 'news', 'action' => 'show', 'news' => "".$value["id"]."")) ?>"><?= $news[0]["title"] ?></a></a></h4>
		                            </div>
								</div>
							</div>
						</div>
					</td>
				</tr>
		</tbody>
		<tfoot>
		</tfoot>
	</table>
</div>
<?php
					}
					?>
<script type="text/javascript">
	function ajaxQuery(id, url){
		$.post(
		  url + id,
		  onAjaxSuccess
		);
	}
	function onAjaxSuccess(data)
		{
		  location.reload();
		}
</script>