
	<?php
	if(isset($this->errorMessage)){

	            echo $this->errorMessage;

	}
	$review = $this->review[0];
	?>
	<br><br>
	<center><h4>Відгук #<?= $review["id"]." до товару #".$review["product_id"] ?></h4></center>
	<div class="pull-right" style="padding-right: 100px;">
		<?php
			if($review["moderal"] == 1){
		?>
			<a class="btn btn-default btn-sm" title="Приховати коментар" id="<?= $review["id"] ?>" onclick="ajaxQuery(this.id, '../../../makevisible/moderal/0/review/')"><i class="glyphicon glyphicon-eye-close"></i></a>
		<?php
			}
			else{
		?>
			<a class="btn btn-success btn-sm" id="<?= $review["id"] ?>" title="Зробити доступним для усіх" onclick="ajaxQuery(this.id, '../../../makevisible/moderal/1/review/')"><i class="glyphicon glyphicon-eye-open"></i></a>
		<?php } ?>
		<a class="btn btn-danger btn-sm" id="<?= $review["id"] ?>" onclick="ajaxQuery(this.id, '../../../delete/review/')"><i class="glyphicon glyphicon-trash"></i></a>
	</div>
	<br>
<div class="container">
  	<div class="row" data-ref="container">
    	<div class="col-lg-12">
    		<div class="form-group">
		        <label><b>Автор:</b></label> <?= $review["author"] ?>
		    </div>
		    <div class="form-group">
		        <label><b>Дата написання:</b></label> <?= $review["date"] ?>
		    </div>
		    <div class="form-group">
		        <label><b>Оцінка:</b></label> <?= $review["mark"] ?>
		    </div>
		   	<div class="form-group">
		        <label>Хороший відгук:</label> <?= $review["good_review"] ?>
		    </div>
		    <div class="form-group">
		        <label>Поганий відгук:</label> <?= $review["bad_review"] ?>
		    </div>
		    <div class="form-group">
		        <label><b>Коментар:</b></label> <?= $review["comment"] ?>
		    </div>
		    <div class="form-group">
		        <label>
		        	<b>
		        		<?php
		        			if($review["moderal"] == 1) echo "Доступно для перегляду";
		        			else echo "Недоступно для перегляду";
		        		?>
		        	</b>
		        </label>
		    </div>
		</div>
	</div>
</div>
<script type="text/javascript">
	function ajaxQuery(id, url){
		$.post(
		  url + id,
		  onAjaxSuccess
		);
	}
	function onAjaxSuccess(data)
		{
		  location.reload();
		}
</script>