
	<?php
	if(isset($this->errorMessage)){

	            echo $this->errorMessage;

	}?>
	<br>
	<center><h4>Додати товар</h4></center>
	<br>
	<?php

	$form = $this->form;
// Remove <dt> from label generation
foreach ($form->getElements() as $element) {
    $element->getDecorator('label')->setOption('tag', null);
    $form->setAttrib('enctype', 'multipart/form-data');
}
?>
<div class="container">
  <div class="row" data-ref="container">
    <div class="col-lg-12">
		<form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>" enctype='multipart/form-data'>
		   	<div class="form-group">
		        <?php echo $form->name->renderLabel() . $form->name->renderViewHelper() ?>
		    </div>
		    <div class="form-group">
	        	<?php echo $form->price->renderLabel() . $form->price->renderViewHelper() ?>
		    </div>
		    <div class="form-group">
	        	<?php echo $form->minidescription->renderLabel() . $form->minidescription->renderViewHelper() ?>
		    </div>
		    <div class="form-group">
	        	<?php echo $form->description->renderLabel() . $form->description->renderViewHelper() ?>
		    </div>
		    <div class="form-group">
	        	<?php echo $form->type->renderLabel() . $form->type->renderViewHelper() ?>
		    </div>
		    <div class="form-group">
	        	<?php echo $form->category->renderLabel() . $form->category->renderViewHelper() ?>
		    </div>
		    <div class="form-group">
	        	<input type="hidden" name="MAX_FILE_SIZE" value="100000" />
	        	<?php /*echo $form->image->renderLabel() . $form->image->renderViewHelper()*/ ?>
		    </div>
		    <div class="form-group">
	        	<?php echo $form->minicharacteristic->renderLabel() . $form->minicharacteristic->renderViewHelper() ?>
		    </div>
		    <div class="form-group">
	        	<?php echo $form->characterstic->renderLabel() . $form->characterstic->renderViewHelper() ?>
		    </div>
		    
		    <?php echo $this->formSubmit('submit', 'Save') ?>
		</form>
	</div>
</div>