<?php
	if(isset($this->errorMessage)){
		echo $this->errorMessage;

	}?>
	<br>
	<center><h4>Додати товар</h4></center>
	<br>
	<?php

	$form = $this->form;
	$product = $this->product;
	$images = $this->images;
// Remove <dt> from label generation
foreach ($form->getElements() as $element) {
    $element->getDecorator('label')->setOption('tag', null);
    $form->setAttrib('enctype', 'multipart/form-data');
}
?>
<div class="container">
  <div class="row" data-ref="container">
    <div class="col-lg-12">
		<form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>" enctype='multipart/form-data'>
		   	<div class="form-group">
		        <?php echo $form->name->renderLabel() . $form->name->setValue($product[0]["name"])->renderViewHelper() ?>
		    </div>
		    <div class="form-group">
	        	<?php echo $form->price->renderLabel() . $form->price->setValue($product[0]["price"])->renderViewHelper() ?>
		    </div>

		    <div class="radio">
			    <label>
			        <input class="form-check-input" type="radio" name="type" id="upload" value="upload">
			        <label for="upload">Вибрати файл з комп'ютера</label>
			    </label>
			   	<div class="upload" style="display: none;">
			   		<?php
				    	foreach ($images as $image) {
				    		if(empty($image["image_name"])){
				    ?>
			        <div id="objects">
				        <div class="form-group" id="add-image1" >
				            <input type="hidden" name="MAX_FILE_SIZE" value="2000000" />
				            <?php echo $form->gallery_img->setValue($image["image"]) ?>
			            </div>
			        </div>
			        <?php
			        		}
			        	}
			        ?>
				    <p id="add-input" class="btn btn-default">Додати ще одну картинку</p>
				</div>
			</div>
			<div class="radio">
			    <label>
			        <input class="form-check-input" type="radio" name="type" id="addurl" value="addurl">
		            <label for="addurl">Вказати URL-адресу</label>
		        </label>
		        <?php
				    foreach ($images as $image) {
				    	if(!empty($image["image_name"])){
				?>
			    <div class="addurl" style="display: none;">  
			    	<div class="form-group">
			        	<?php echo $form->img_name->renderLabel() . $form->img_name->setValue($image["image_name"])->renderViewHelper() ?>
			        	 <p>Наприклад: Картинка</p>
				    </div>  
				     <div class="form-group">
			        	<?php echo $form->img_url->renderLabel() . $form->img_url->setValue($image["image"])->renderViewHelper() ?>
			        	<p>Наприклад: https://some_image.com/example.jpg</p>
				    </div>
			    </div>
			    <?php
			    		}
			    	}
			    ?>
			    <div class="addurl">  
			    	<div class="form-group">
			        	<?php echo $form->img_name->renderLabel() . $form->img_name->renderViewHelper() ?>
			        	 <p>Наприклад: Картинка</p>
				    </div>  
				     <div class="form-group">
			        	<?php echo $form->img_url->renderLabel() . $form->img_url->renderViewHelper() ?>
			        	<p>Наприклад: https://some_image.com/example.jpg</p>
				    </div>
			    </div>
			</div>

		    <div class="form-group">
	        	<?php echo $form->minidescription->renderLabel() . $form->minidescription->setValue($product[0]["minidescription"])->renderViewHelper() ?>
		    </div>
		    <div class="form-group">
	        	<?php echo $form->description->renderLabel() . $form->description->setValue($product[0]["description"])->renderViewHelper() ?>
		    </div>
		    <div class="form-group">
	        	<?php echo $form->type->renderLabel() . $form->type->setValue($product[0]["type"])->renderViewHelper() ?>
		    </div>
		    <div class="form-group">
	        	<?php echo $form->category->renderLabel() . $form->category->setValue($product[0]["category"])->renderViewHelper() ?>
		    </div>
		    <div class="form-group">
	        	<input type="hidden" name="MAX_FILE_SIZE" value="100000" />
	        	<?php /*echo $form->image->renderLabel() . $form->image->renderViewHelper()*/ ?>
		    </div>
		    <div class="form-group">
	        	<?php echo $form->minicharacteristic->renderLabel() . $form->minicharacteristic->setValue($product[0]["minicharacteristic"])->renderViewHelper() ?>
		    </div>
		    <div class="form-group">
	        	<?php echo $form->characterstic->renderLabel() . $form->characterstic->setValue($product[0]["characterstic"])->renderViewHelper() ?>
		    </div>
		    
		    <?php echo $this->formSubmit('submit', 'Save') ?>
		</form>
	</div>
</div>

<script>
    $("input[name=type]").click(function() {
        if($('input[name=type]:checked').val() == "upload"){
            $(".addurl").hide();
            $(".upload").show();
        }
        else if($('input[name=type]:checked').val() == "addurl"){
            $(".addurl").show();
            $(".upload").hide();
        }
    });
    $(document).ready(
    function(){
        //додавання нової картинки
        var count_input = 1;
        $("#add-input").click(function(){
            count_input++;
            $("<div id='add-image"+count_input+"' class='form-group'><input type='hidden' name='MAX_FILE_SIZE' value='2000000'/><input type='file' class='form-control' name='gallery_img[]'/><a class='delete-input' rel='"+count_input+"'>Видалити</a></div>").fadeIn(300).appendTo("#objects"); 
        });
        //видалення картинки
        $(document).on("click", ".delete-input", function(){
            var rel = $(this).attr("rel");
            $("#add-image"+rel).fadeOut(300, function(){
                $("#add-image"+rel).remove();
            });
        });
        $("td.delete").click(function() {
            document.getElementById('delete_id').value = $('div.id').html();
        });
        $("[data-toggle=tooltip]").tooltip();
    }
);
</script>