<br><br><br>
<div class="container">
	<div class="row">
        <?= var_dump($this->myarr) ?>
		<div id="block-step">
            <div id="name-step">
                <ul class="list-inline">
                    <li><a href="<?php echo $this->url(array('module' => 'shop', 'controller'=>'basket','action'=>'show'));?>">1. Корзина товарів</a></li>
                    <li><span class="glyphicon glyphicon-arrow-right"></span></li>
                    <li><a href="<?php echo $this->url(array('module' => 'shop', 'controller'=>'order','action'=>'contactinfo'));?>" >2. Контактна інформація</a></li>
                    <li><span class="glyphicon glyphicon-arrow-right"></span></li>
                    <li><a href="" class="active">3. Завершення</a></li>
                </ul>
            </div>
            <p>Крок 3 із 3</p>
        </div>
        <br>
        <div class="receipt-main col-xs-10 col-sm-10 col-md-6 col-xs-offset-1 col-sm-offset-1 col-md-offset-3">	
			<div class="row">
				<div class="receipt-header receipt-header-mid">
					<div class="col-xs-8 col-sm-8 col-md-8 text-left">
						<div class="receipt-right">
                            <p><b>ПІБ: </b><?= $this->customer_data["pib"] ?></p>
							<p><b>Електронна пошта: </b><?= $this->customer_data["email"] ?></p>
                            <p><b>Номер телефону: </b><?= $this->customer_data["phone"] ?></p>
                            <p><b>Місто: </b><?= $this->customer_data["address"] ?></p>
                            <p><b>Спосіб доставки: </b><?= $this->customer_data["delivery_type"] ?></p>
                            <p><b>Тип оплати: </b><?= $this->customer_data["pay_type"] ?></p>
                            <p><b>Примітка: </b><?= $this->customer_data["note"] ?></p>
						</div>
					</div>
				</div>
            </div>
			
            <div>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Опис</th>
                            <th>Кількість</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="col-md-9">Кількість товарів</td>
                            <td class="col-md-3"><i class="fa fa-inr"></i><?= $this->count ?> шт.</td>
                        </tr>
                        <tr>
                            <td class="col-md-9">Загальна вартість</td>
                            <td class="col-md-3"><i class="fa fa-inr"></i><?= number_format($this->sum, 2, ',', ' '); ?> грн.</td>
                        </tr>
                    </tbody>
                </table>
            </div>
			
			<div class="row">
				<div class="receipt-header receipt-header-mid receipt-footer">
					<div class="col-xs-8 col-sm-8 col-md-8 text-left">
						<div class="receipt-right">
							<p><b>Дата замовлення: </b><?= date("d-m-o") ?></p>
						</div>
					</div>
					<div class="col-xs-4 col-sm-4 col-md-4">
						<div class="receipt-left">
                            <form method="post">
							     <?php echo $this->formSubmit('submit', 'Підтвердити', array("class" => "btn btn-primary btn-block")) ?>
                            </form>
						</div>
					</div>
				</div>
            </div>
			
        </div>    
	</div>
</div>

