<style type="text/css">
	
</style>
<?php
	if(isset($this->errorMessage)){
		echo $this->errorMessage;

	}?>
	<br>
	<br>
	<?php

	$form = $this->form;
// Remove <dt> from label generation
foreach ($form->getElements() as $element) {
    $element->getDecorator('label')->setOption('tag', null);
    $form->setAttrib('enctype', 'multipart/form-data');
}
?>
<div class="container">
  <div class="row" data-ref="container">
  	<div id="block-step">
		<div id="name-step">
            <ul class="list-inline">
	          	<li><a href="">1. Корзина товарів</a></li>
	          	<li><span class="glyphicon glyphicon-arrow-right"></span></li>
	          	<li><a href="" class="active">2. Контактна інформація</a></li>
	          	<li><span class="glyphicon glyphicon-arrow-right"></span></li>
	          	<li><a href="">3. Завершення</a></li>
	        </ul>
        </div>
        <p>Крок 2 із 3</p>
    </div>
    <br>
    <div class="col-lg-12">
		<form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>" enctype='multipart/form-data'>
			<div class="form-group">
		        <h4>Способи доставки:</h4>
		    </div>
			<div class="radio">
			    <label>
			    	<?= $form->delivery_type->renderViewHelper() ?>
			    </label>
			</div>
			<br>
			<div class="form-group">
		        <h4 class="title-h3">Інформація для доставки:</h4>
		    </div>
		   	<div class="form-group">
		        <?php echo $form->pib->renderLabel() . $form->pib->renderViewHelper() ?>
		        <i>Приклад: Іванов Іван Іванович</i>
		    </div>
		    <div class="form-group">
		        <?php echo $form->email->renderLabel() . $form->email->renderViewHelper() ?>
		        <i>Приклад: ivanov@gmail.com</i>
		    </div>
		    <div class="form-group">
		        <?php echo $form->phone->renderLabel() . $form->phone->renderViewHelper() ?>
		        <i>Приклад: 380505050505</i>
		    </div>
		    <div class="form-group">
		        <?php echo $form->address->renderLabel() . $form->address->renderViewHelper() ?>
		        <i>Приклад: м. Київ, вул. Іванова, буд. 1</i>
		    </div>
		    <div class="radio">
		    	<strong><?= $form->pay_type->renderLabel() ?></strong><br>
			    <label>
			    	<?= $form->pay_type->renderViewHelper() ?>
			    </label>
			</div>
		    <div class="form-group">
		    	<?php echo $form->note->renderLabel() ?><br>
		    	<i>Уточніть інформацію про заказ. Наприклад, зручний час для дзвінка нашого менеджера</i>
	        	<?= $form->note->renderViewHelper() ?>
		    </div>
		    <?php echo $this->formSubmit('submit', 'Далі') ?>
		</form>
	</div>
</div>