<style type="text/css">
	
</style>
<?php
	if(isset($this->errorMessage)){
		echo $this->errorMessage;

	}?>
	<br>
	<br>
	<?php

	$form = $this->form;
// Remove <dt> from label generation
foreach ($form->getElements() as $element) {
    $element->getDecorator('label')->setOption('tag', null);
    $form->setAttrib('enctype', 'multipart/form-data');
}
?>
<div class="container">
  <div class="row" data-ref="container">
  	<div id="block-step">
		<div id="name-step">
            <ul class="list-inline">
	          	<li><a href="<?php echo $this->url(array('module' => 'shop', 'controller'=>'basket','action'=>'show'));?>">1. Корзина товарів</a></li>
	          	<li><span class="glyphicon glyphicon-arrow-right"></span></li>
	          	<li><a href="" class="active">2. Контактна інформація</a></li>
	          	<li><span class="glyphicon glyphicon-arrow-right"></span></li>
	          	<li><a href="">3. Завершення</a></li>
	        </ul>
        </div>
        <p>Крок 2 із 3</p>
    </div>
    <br>
    <div class="col-lg-12">
		<form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>" enctype='multipart/form-data'>
			<?php
            $user = Zend_Auth::getInstance();
            if (!$user->hasIdentity()){ ?>
            <div class="form-group">
		        <div class="alert alert-warning" role="alert">
		        	Для того, щоб проглянути Ваші замовлення <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'customer', 'action' => 'signup')) ?>">зареєструйтесь</a> або <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'customer', 'action' => 'login')) ?>">увійдіть</a>
		        </div>
		    </div>
		    <?php } ?>
			<div class="form-group">
		        <h4>Способи доставки:</h4>
		    </div>
			<div class="radio">
			    <label>
			    	<?= $form->delivery_type->renderViewHelper() ?>
			    </label>
			</div>
			<br>
			<div class="form-group">
		        <h4 class="title-h3">Інформація для доставки:</h4>
		    </div>
		   	<div class="form-group">
		        <?php 
		        	if ($user->hasIdentity()){
		        		$customer = $user->getIdentity()->firstname." ".$user->getIdentity()->lastname;
		        		echo $form->pib->renderLabel() . $form->pib->setValue($customer)->renderViewHelper();
		        	}
		        	else{
		        		echo $form->pib->renderLabel() . $form->pib->renderViewHelper();
		        	}
		        ?>
		        <i>Приклад: Іванов Іван Іванович</i>
		    </div>
		    <?php
            if (!$user->hasIdentity()){ ?>
		    <div class="form-group">
		        <div class="alert alert-warning" role="alert">Дане замовлення буде прикріплене до Вашої електронної пошти. Для того, щоб проглянути Ваші замовлення <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'customer', 'action' => 'signup')) ?>">зареєструйтесь</a> або <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'customer', 'action' => 'login')) ?>">увійдіть</a></div>
		    </div>
		    <?php } ?>
		    <div class="form-group">
		    	<?php 
		        	if ($user->hasIdentity()){
		        		echo $form->email->renderLabel() . $form->email->setValue($user->getIdentity()->email)->renderViewHelper();
		        	}
		        	else{
		        		echo $form->email->renderLabel() . $form->email->renderViewHelper();
		        	}
		        ?>
		        <i>Приклад: ivanov@gmail.com</i>
		    </div>
		    <div class="form-group">
		        <?php echo $form->phone->renderLabel() . $form->phone->renderViewHelper() ?>
		        <i>Приклад: 380505050505</i>
		    </div>
		    <div class="form-group">
		    	<?php 
		        	if ($user->hasIdentity()){
		        		echo $form->address->renderLabel() . $form->address->setValue($user->getIdentity()->city)->renderViewHelper();
		        	}
		        	else{
		        		echo $form->address->renderLabel() . $form->address->renderViewHelper();
		        	}
		        ?>
		        <i>Приклад: м. Київ, вул. Іванова, буд. 1</i>
		    </div>
		    <div class="radio">
		    	<strong><?= $form->pay_type->renderLabel() ?></strong><br>
			    <label>
			    	<?= $form->pay_type->renderViewHelper() ?>
			    </label>
			</div>
		    <div class="form-group">
		    	<?php echo $form->note->renderLabel() ?><br>
		    	<i>Уточніть інформацію про заказ. Наприклад, зручний час для дзвінка нашого менеджера</i>
	        	<?= $form->note->renderViewHelper() ?>
		    </div>
		    <?php echo $this->formSubmit('submit', 'Далі', array("class" => "btn btn-default")) ?>
		</form>
	</div>
</div>

