<br><br>
<div class="container">
<h2>Відгуки до товара #<?= $this->id ?> </h2>
<table id="cart" class="table table-hover table-condensed">
    	<thead>
			<tr>
				<th style="width:10%">Дата</th>
				<th style="width:20%">Замовник</th>
				<th style="width:20%">Cпосіб доставки</th>
				<th style="width:20%">Статус оплати</th>
				<th style="width:20%">Тип оплати</th>
				<th style="width:10%">Статус</th>
			</tr>
		</thead>
		<tbody>
			<?php

				if(count($this->orders) > 1){

	        		foreach ($this->orders as $key => $value) {
	      		?>
				<tr>
					<td>
						<?= $value["datetime"] ?>
					</td>
					<td>
						<?= $value["pib"] ?>
					</td>
					<td>
						<?= $value["delivery_type"] ?>
					</td>
					<td>
						<?php
						if($value["payed"] == 1) echo "Оплачено";
						else echo "Неоплачено"; 
						?>
					</td>
					<td>
						<?= $value["pay_type"] ?>
					</td>
					<td>
						<?= $value["status"] ?>
					</td>
					<td class="actions" data-th="">
						<a class="btn btn-primary btn-block" href="<?php echo $this->url(array('module' => 'default', 'controller'=>'orders','action'=>'show', 'order' => "{$value["id"]}"));?>">Переглянути</a>
						<a class="btn btn-danger btn-block" id="<?= $value["id"] ?>" onclick="ajaxQuery('<?php echo $this->url(array('module' => 'default', 'controller'=>'orders','action'=>'cancel', 'order' => "{$value["id"]}"));?>')">Скасувати замовлення</a>							
					</td>
				</tr>
				<?php
					}
					?>
		</tbody>
	</table>
	<!--
	<ul class="pager">
	        <li>Показати товарів: 
	          <select id="show_el" name="show" style="color: black;">
	            <option < ?php if($this->show == 5) echo "selected"; ?> value ="5">5</option>
	            <option < ?php if($this->show == 10) echo "selected"; ?> value ="10">10</option>
	            <option < ?php if($this->show == 25) echo "selected"; ?> value="25">25</option>
	            <option < ?php if($this->show == 50) echo "selected"; ?> value="50">50</option>
	            <option < ?php if($this->show == 100) echo "selected"; ?> value="100">100</option>
	          </select>
	        </li>
	        
	        < php
	          echo $this->paginationControl($this->news, "sliding", "pagination.phtml");
	        ?>
	      </ul>
	     -->
</div>
					<?php
				}
				else if(count($this->orders) == 1){
						$value = $this->orders[0];
	      		?>
				<tr>
					<td>
						<?= $value["datetime"] ?>
					</td>
					<td>
						<?= $value["pib"] ?>
					</td>
					<td>
						<?= $value["delivery_type"] ?>
					</td>
					<td>
						<?php
						if($value["payed"] == 1) echo "Оплачено";
						else echo "Неоплачено"; 
						?>
					</td>
					<td>
						<?= $value["pay_type"] ?>
					</td>
					<td>
						<?= $value["status"] ?>
					</td>
					<td class="actions" data-th="">
						<a class="btn btn-primary btn-block" href="<?php echo $this->url(array('module' => 'default', 'controller'=>'orders','action'=>'show', 'order' => "{$value["id"]}"));?>">Переглянути</a>
						<a class="btn btn-danger btn-block" id="<?= $value["id"] ?>" onclick="ajaxQuery('<?php echo $this->url(array('module' => 'default', 'controller'=>'orders','action'=>'cancel', 'order' => "{$value["id"]}"));?>')">Скасувати замовлення</a>							
					</td>
				</tr>
		</tbody>
		<tfoot>
		</tfoot>
	</table>
</div>
<?php
					}
					?>
<script type="text/javascript">
	function ajaxQuery(id, url){
		$.post(
		  url + id,
		  onAjaxSuccess
		);
	}
	function onAjaxSuccess(data)
		{
		  location.reload();
		}
</script>

